I 03-17 21:19:18 controller.py:59] DAG:
I 03-17 21:19:18 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 21:19:18 controller.py:59]   resources: {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}]
I 03-17 21:19:18 controller.py:195] Submitted managed job 185 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-21-19-18-629352_compute-text-vectors_185-0
I 03-17 21:19:18 controller.py:199] Started monitoring.
I 03-17 21:19:18 state.py:451] Launching the spot cluster...
I 03-17 21:19:18 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 21:19:19 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:19:19 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 21:19:19 optimizer.py:749] 
I 03-17 21:19:19 optimizer.py:884] Considered resources (1 node):
I 03-17 21:19:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:19:19 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:19:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:19:19 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1b   0.22       [32m   âœ”[0m     
I 03-17 21:19:19 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:19:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:19:20 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1b).
[2mW 03-17 21:25:31 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:25:33 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:25:33 cloud_vm_ray_backend.py:2097] 
W 03-17 21:25:33 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:25:33 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:25:33 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 21:25:33 optimizer.py:749] 
I 03-17 21:25:33 optimizer.py:884] Considered resources (1 node):
I 03-17 21:25:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:25:33 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:25:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:25:33 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1a   0.25       [32m   âœ”[0m     
I 03-17 21:25:33 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:25:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:25:33 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a).
[2mW 03-17 21:42:25 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:42:26 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:42:26 cloud_vm_ray_backend.py:2097] 
W 03-17 21:42:26 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:42:26 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:42:26 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:42:26 optimizer.py:749] 
I 03-17 21:42:26 optimizer.py:884] Considered resources (1 node):
I 03-17 21:42:26 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:42:26 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 21:42:26 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:42:26 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2d   0.25       [32m   âœ”[0m     
I 03-17 21:42:26 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 21:42:26 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:42:26 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2d).
W 03-17 21:54:28 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:54:28 cloud_vm_ray_backend.py:2097] 
W 03-17 21:54:28 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:54:29 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:54:29 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:54:29 optimizer.py:749] 
I 03-17 21:54:29 optimizer.py:884] Considered resources (1 node):
I 03-17 21:54:29 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:54:29 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 21:54:29 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:54:29 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2a   0.27       [32m   âœ”[0m     
I 03-17 21:54:29 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 21:54:29 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:54:29 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a).
[2mW 03-17 21:58:10 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
W 03-17 21:58:11 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:58:11 cloud_vm_ray_backend.py:2097] 
W 03-17 21:58:11 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:58:11 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:58:11 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:58:11 optimizer.py:749] 
I 03-17 21:58:11 optimizer.py:884] Considered resources (1 node):
I 03-17 21:58:11 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:58:11 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:58:11 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:58:11 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1b    0.30       [32m   âœ”[0m     
I 03-17 21:58:11 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:58:11 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:58:11 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1b).
[2mW 03-17 22:01:35 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1c, us-east-1d.[0m
W 03-17 22:01:35 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:01:35 cloud_vm_ray_backend.py:2097] 
W 03-17 22:01:35 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:01:35 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:01:35 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:01:35 optimizer.py:749] 
I 03-17 22:01:35 optimizer.py:884] Considered resources (1 node):
I 03-17 22:01:35 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:01:35 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:01:35 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:01:35 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2c    0.31       [32m   âœ”[0m     
I 03-17 22:01:35 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:01:35 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:01:36 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2c).
[2mW 03-17 22:02:19 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-2a, us-east-2b.[0m
W 03-17 22:02:19 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:02:19 cloud_vm_ray_backend.py:2097] 
W 03-17 22:02:19 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:02:19 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:02:19 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:02:19 optimizer.py:749] 
I 03-17 22:02:19 optimizer.py:884] Considered resources (1 node):
I 03-17 22:02:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:02:19 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:02:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:02:19 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2b    0.32       [32m   âœ”[0m     
I 03-17 22:02:19 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:02:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:02:19 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2b).
[2mW 03-17 22:02:48 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-2b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-2a, us-east-2c.[0m
W 03-17 22:02:48 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:02:48 cloud_vm_ray_backend.py:2097] 
W 03-17 22:02:48 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:02:48 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:02:48 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:02:48 optimizer.py:749] 
I 03-17 22:02:48 optimizer.py:884] Considered resources (1 node):
I 03-17 22:02:48 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:02:48 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:02:48 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:02:48 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1a   0.33       [32m   âœ”[0m     
I 03-17 22:02:48 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:02:48 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:02:48 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a).
[2mW 03-17 22:02:53 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:02:54 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:02:54 cloud_vm_ray_backend.py:2097] 
W 03-17 22:02:54 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:02:54 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:02:54 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:02:54 optimizer.py:749] 
I 03-17 22:02:54 optimizer.py:884] Considered resources (1 node):
I 03-17 22:02:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:02:54 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:02:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:02:54 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1c    0.34       [32m   âœ”[0m     
I 03-17 22:02:54 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:02:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:02:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1c).
[2mE 03-17 22:02:55 config.py:46] SKYPILOT_ERROR_NO_NODES_LAUNCHED: No usable subnets matching availability zone ['us-east-1c'] found. Choose a different availability zone or try manually creating an instance in your specified region to populate the list of subnets and trying this again. If you have set `use_internal_ips`, check that this zone has a subnet that (1) has the substring 'private' in its name tag and (2) does not assign public IPs (`map_public_ip_on_launch` is False).[0m
W 03-17 22:02:56 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:02:56 cloud_vm_ray_backend.py:2097] 
W 03-17 22:02:56 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:02:56 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:02:56 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:02:56 optimizer.py:749] 
I 03-17 22:02:56 optimizer.py:884] Considered resources (1 node):
I 03-17 22:02:56 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:02:56 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:02:56 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:02:56 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1b   0.34       [32m   âœ”[0m     
I 03-17 22:02:56 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:02:56 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:02:56 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1b).
[2mW 03-17 22:03:01 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:03:01 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:03:01 cloud_vm_ray_backend.py:2097] 
W 03-17 22:03:01 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:03:02 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:03:02 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:03:02 optimizer.py:749] 
I 03-17 22:03:02 optimizer.py:884] Considered resources (1 node):
I 03-17 22:03:02 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:02 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:03:02 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:02 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2a    0.34       [32m   âœ”[0m     
I 03-17 22:03:02 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:03:02 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:03:02 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2a).
[2mW 03-17 22:03:09 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:03:10 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:03:10 cloud_vm_ray_backend.py:2097] 
W 03-17 22:03:10 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:03:10 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:03:10 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:03:10 optimizer.py:749] 
I 03-17 22:03:10 optimizer.py:884] Considered resources (1 node):
I 03-17 22:03:10 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:10 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:03:10 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:10 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3c    0.35       [32m   âœ”[0m     
I 03-17 22:03:10 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:03:10 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:03:10 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3c).
[2mW 03-17 22:03:17 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (eu-west-3c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-3b.[0m
W 03-17 22:03:18 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:03:18 cloud_vm_ray_backend.py:2097] 
W 03-17 22:03:18 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:03:18 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:03:18 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:03:18 optimizer.py:749] 
I 03-17 22:03:18 optimizer.py:884] Considered resources (1 node):
I 03-17 22:03:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:18 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:03:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:18 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1a   0.35       [32m   âœ”[0m     
I 03-17 22:03:18 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:03:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:03:18 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a).
[2mW 03-17 22:03:30 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:03:31 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:03:31 cloud_vm_ray_backend.py:2097] 
W 03-17 22:03:31 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:03:31 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:03:31 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:03:31 optimizer.py:749] 
I 03-17 22:03:31 optimizer.py:884] Considered resources (1 node):
I 03-17 22:03:31 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:31 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:03:31 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:31 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2b    0.36       [32m   âœ”[0m     
I 03-17 22:03:31 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:03:31 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:03:31 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2b).
[2mW 03-17 22:03:38 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:03:39 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:03:39 cloud_vm_ray_backend.py:2097] 
W 03-17 22:03:39 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:03:40 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:03:40 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:03:40 optimizer.py:749] 
I 03-17 22:03:40 optimizer.py:884] Considered resources (1 node):
I 03-17 22:03:40 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:03:40 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:03:40 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:03:40 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2c   0.36       [32m   âœ”[0m     
I 03-17 22:03:40 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:03:40 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:03:40 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2c).
[2mW 03-17 22:03:53 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-southeast-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-southeast-2a.[0m
W 03-17 22:03:54 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-southeast-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:03:54 cloud_vm_ray_backend.py:2097] 
W 03-17 22:03:54 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:03:54 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:03:54 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:03:54 optimizer.py:749] 
I 03-17 22:03:54 optimizer.py:884] Considered resources (1 node):
I 03-17 22:03:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:54 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:03:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:03:54 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1d    0.37       [32m   âœ”[0m     
I 03-17 22:03:54 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:03:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:03:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1d).
[2mW 03-17 22:06:59 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:07:00 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:07:00 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:00 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:00 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:00 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:07:00 optimizer.py:749] 
I 03-17 22:07:00 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:00 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:07:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:00 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2b    0.37       [32m   âœ”[0m     
I 03-17 22:07:00 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:07:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:00 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2b).
[2mW 03-17 22:07:09 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:07:10 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:07:10 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:10 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:10 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:10 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:07:10 optimizer.py:749] 
I 03-17 22:07:10 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:10 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:10 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:07:10 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:10 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1b   0.37       [32m   âœ”[0m     
I 03-17 22:07:10 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:07:10 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:10 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1b).
[2mW 03-17 22:07:21 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:07:21 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:07:21 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:21 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:22 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:22 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:07:22 optimizer.py:749] 
I 03-17 22:07:22 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:22 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:07:22 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:07:22 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:07:22 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2a   0.38       [32m   âœ”[0m     
I 03-17 22:07:22 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:07:22 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:22 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2a).
[2mW 03-17 22:07:33 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:07:34 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-southeast-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:07:34 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:34 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:34 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:34 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:07:34 optimizer.py:749] 
I 03-17 22:07:34 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:34 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:34 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:07:34 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:34 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3b    0.38       [32m   âœ”[0m     
I 03-17 22:07:34 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:07:34 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:34 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3b).
[2mW 03-17 22:07:42 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:07:43 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:07:43 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:43 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:43 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:43 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:07:43 optimizer.py:749] 
I 03-17 22:07:43 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:43 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:43 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:07:43 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:43 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1a    0.39       [32m   âœ”[0m     
I 03-17 22:07:43 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:07:43 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:43 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1a).
[2mW 03-17 22:08:53 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:08:53 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:08:53 cloud_vm_ray_backend.py:2097] 
W 03-17 22:08:53 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:08:53 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:08:53 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:08:53 optimizer.py:749] 
I 03-17 22:08:53 optimizer.py:884] Considered resources (1 node):
I 03-17 22:08:53 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:08:53 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:08:53 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:08:53 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2a    0.40       [32m   âœ”[0m     
I 03-17 22:08:53 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:08:53 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:08:53 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2a).
[2mW 03-17 22:15:06 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:15:07 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:15:07 cloud_vm_ray_backend.py:2097] 
W 03-17 22:15:07 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:15:07 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:15:07 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:15:07 optimizer.py:749] 
I 03-17 22:15:07 optimizer.py:884] Considered resources (1 node):
I 03-17 22:15:07 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:15:07 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:15:07 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:15:07 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-central-1b   0.40       [32m   âœ”[0m     
I 03-17 22:15:07 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:15:07 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:15:07 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1b).
[2mW 03-17 22:15:17 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:15:18 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-central-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:15:18 cloud_vm_ray_backend.py:2097] 
W 03-17 22:15:18 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:15:18 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:15:18 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:15:18 optimizer.py:749] 
I 03-17 22:15:18 optimizer.py:884] Considered resources (1 node):
I 03-17 22:15:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:15:18 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:15:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:15:18 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2d    0.41       [32m   âœ”[0m     
I 03-17 22:15:18 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:15:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:15:18 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2d).
[2mW 03-17 22:15:26 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:15:27 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:15:27 cloud_vm_ray_backend.py:2097] 
W 03-17 22:15:27 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:15:27 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:15:27 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:15:27 optimizer.py:749] 
I 03-17 22:15:27 optimizer.py:884] Considered resources (1 node):
I 03-17 22:15:27 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:15:27 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:15:27 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:15:27 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-central-1a   0.41       [32m   âœ”[0m     
I 03-17 22:15:27 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:15:27 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:15:27 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1a).
[2mW 03-17 22:15:44 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:15:45 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-central-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:15:45 cloud_vm_ray_backend.py:2097] 
W 03-17 22:15:45 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:15:45 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:15:45 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:15:45 optimizer.py:749] 
I 03-17 22:15:45 optimizer.py:884] Considered resources (1 node):
I 03-17 22:15:45 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:15:45 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:15:45 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:15:45 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2c    0.41       [32m   âœ”[0m     
I 03-17 22:15:45 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:15:45 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:15:45 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2c).
[2mW 03-17 22:15:53 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:15:53 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:15:53 cloud_vm_ray_backend.py:2097] 
W 03-17 22:15:53 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:15:54 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:15:54 optimizer.py:749] [1mEstimated cost: [0m$0.5 / hour
I 03-17 22:15:54 optimizer.py:749] 
I 03-17 22:15:54 optimizer.py:884] Considered resources (1 node):
I 03-17 22:15:54 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:15:54 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:15:54 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:15:54 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-1a   0.46       [32m   âœ”[0m     
I 03-17 22:15:54 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:15:54 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:15:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-1[0m (ap-northeast-1a).
[2mW 03-17 22:16:06 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:16:07 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:16:07 cloud_vm_ray_backend.py:2097] 
W 03-17 22:16:07 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:16:07 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:16:07 optimizer.py:749] [1mEstimated cost: [0m$0.5 / hour
I 03-17 22:16:07 optimizer.py:749] 
I 03-17 22:16:07 optimizer.py:884] Considered resources (1 node):
I 03-17 22:16:07 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:16:07 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:16:07 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:16:07 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-1c   0.48       [32m   âœ”[0m     
I 03-17 22:16:07 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:16:07 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:16:07 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-1[0m (ap-northeast-1c).
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Waiting for SSH access[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:16:34 provisioner.py:451] [2mâ””â”€â”€ [0m[2mInstance is up.[0m
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (1/3 - initializing)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (2/3 - dependencies)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (3/3 - runtime)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:17:11 provisioner.py:632] [0m[32mâœ“ Cluster launched: compute-text-vectors-185.[0m  [2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 22:17:11 execution.py:332] [0mâš™ï¸Ž Syncing files.
<sky-payload>"<rich_init>[bold cyan]Syncing files[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing files[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Syncing files[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing file mounts[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/file_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:17:12 backend_utils.py:1315]   [2mSyncing (to 1 node): s3://skypilot-filemounts-root-726f1974-eosmaz43/job-eosmaz43/workdir -> ~/sky_workdir[0m
I 03-17 22:17:15 cloud_vm_ray_backend.py:4801] [0m[32mâœ“ Synced file_mounts.[0m  [2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/file_mounts.log[0m
<sky-payload>"<rich_update>[bold cyan]Mounting 1 storage[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/storage_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:17:15 backend_utils.py:1315]   [2mMounting (to 1 node): s3://sky-text-embeddings-multi-cluster-final-2 -> /output[0m
I 03-17 22:17:18 cloud_vm_ray_backend.py:4892] [0m[32mâœ“ Storage mounted.[0m  [2mView logs: sky api logs -l sky-2025-03-17-21-19-19-321891/storage_mounts.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Running setup[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Running setup[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Running setup[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
I 03-17 22:17:21 cloud_vm_ray_backend.py:3357] [0m[32mâœ“ Setup detached.[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Submitting job[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Submitting job[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Submitting job[/]</rich_start>"</sky-payload>
I 03-17 22:17:22 cloud_vm_ray_backend.py:3546] Multiple resources are specified for the task, using: AWS([Spot], cpus=4, {'L4': 1})
I 03-17 22:17:24 cloud_vm_ray_backend.py:3460] [0mâš™ï¸Ž Job submitted, ID: 1
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 22:17:24 recovery_strategy.py:289] Managed job cluster launched.
I 03-17 22:17:28 utils.py:131] === Checking the job status... ===
I 03-17 22:17:29 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:17:29 utils.py:140] ==================================
I 03-17 22:17:30 state.py:471] Job started.
I 03-17 22:17:50 utils.py:131] === Checking the job status... ===
I 03-17 22:17:51 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:17:51 utils.py:140] ==================================
I 03-17 22:18:11 utils.py:131] === Checking the job status... ===
I 03-17 22:18:12 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:18:12 utils.py:140] ==================================
I 03-17 22:18:32 utils.py:131] === Checking the job status... ===
I 03-17 22:18:33 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:18:33 utils.py:140] ==================================
I 03-17 22:18:53 utils.py:131] === Checking the job status... ===
I 03-17 22:18:54 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:18:54 utils.py:140] ==================================
I 03-17 22:19:14 utils.py:131] === Checking the job status... ===
I 03-17 22:19:15 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:19:15 utils.py:140] ==================================
I 03-17 22:19:35 utils.py:131] === Checking the job status... ===
I 03-17 22:19:36 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:19:36 utils.py:140] ==================================
I 03-17 22:19:57 utils.py:131] === Checking the job status... ===
I 03-17 22:19:57 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:19:57 utils.py:140] ==================================
I 03-17 22:20:18 utils.py:131] === Checking the job status... ===
I 03-17 22:20:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:20:19 utils.py:140] ==================================
I 03-17 22:20:39 utils.py:131] === Checking the job status... ===
I 03-17 22:20:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:20:40 utils.py:140] ==================================
I 03-17 22:21:00 utils.py:131] === Checking the job status... ===
I 03-17 22:21:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:21:01 utils.py:140] ==================================
I 03-17 22:21:21 utils.py:131] === Checking the job status... ===
I 03-17 22:21:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:21:22 utils.py:140] ==================================
I 03-17 22:21:42 utils.py:131] === Checking the job status... ===
I 03-17 22:21:43 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:21:43 utils.py:140] ==================================
I 03-17 22:22:04 utils.py:131] === Checking the job status... ===
I 03-17 22:22:05 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:22:05 utils.py:140] ==================================
I 03-17 22:22:25 utils.py:131] === Checking the job status... ===
I 03-17 22:22:26 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:22:26 utils.py:140] ==================================
I 03-17 22:22:46 utils.py:131] === Checking the job status... ===
I 03-17 22:22:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:22:47 utils.py:140] ==================================
I 03-17 22:23:07 utils.py:131] === Checking the job status... ===
I 03-17 22:23:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:23:08 utils.py:140] ==================================
I 03-17 22:23:28 utils.py:131] === Checking the job status... ===
I 03-17 22:23:31 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:23:31 utils.py:140] ==================================
I 03-17 22:23:51 utils.py:131] === Checking the job status... ===
I 03-17 22:23:54 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:23:54 utils.py:140] ==================================
I 03-17 22:24:14 utils.py:131] === Checking the job status... ===
I 03-17 22:24:16 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:24:16 utils.py:140] ==================================
I 03-17 22:24:36 utils.py:131] === Checking the job status... ===
I 03-17 22:24:37 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:24:37 utils.py:140] ==================================
I 03-17 22:24:57 utils.py:131] === Checking the job status... ===
I 03-17 22:24:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:24:58 utils.py:140] ==================================
I 03-17 22:25:18 utils.py:131] === Checking the job status... ===
I 03-17 22:25:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:25:19 utils.py:140] ==================================
I 03-17 22:25:39 utils.py:131] === Checking the job status... ===
I 03-17 22:25:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:25:40 utils.py:140] ==================================
I 03-17 22:26:00 utils.py:131] === Checking the job status... ===
I 03-17 22:26:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:26:01 utils.py:140] ==================================
I 03-17 22:26:21 utils.py:131] === Checking the job status... ===
I 03-17 22:26:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:26:22 utils.py:140] ==================================
I 03-17 22:26:42 utils.py:131] === Checking the job status... ===
I 03-17 22:26:43 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:26:43 utils.py:140] ==================================
I 03-17 22:27:03 utils.py:131] === Checking the job status... ===
I 03-17 22:27:04 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:27:04 utils.py:140] ==================================
I 03-17 22:27:24 utils.py:131] === Checking the job status... ===
I 03-17 22:27:25 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:27:25 utils.py:140] ==================================
I 03-17 22:27:45 utils.py:131] === Checking the job status... ===
I 03-17 22:27:46 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:27:46 utils.py:140] ==================================
I 03-17 22:28:06 utils.py:131] === Checking the job status... ===
I 03-17 22:28:07 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:28:07 utils.py:140] ==================================
I 03-17 22:28:27 utils.py:131] === Checking the job status... ===
I 03-17 22:28:28 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:28:28 utils.py:140] ==================================
I 03-17 22:28:48 utils.py:131] === Checking the job status... ===
I 03-17 22:28:49 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:28:49 utils.py:140] ==================================
I 03-17 22:29:09 utils.py:131] === Checking the job status... ===
I 03-17 22:29:10 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:29:10 utils.py:140] ==================================
I 03-17 22:29:30 utils.py:131] === Checking the job status... ===
I 03-17 22:29:31 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:29:31 utils.py:140] ==================================
I 03-17 22:29:51 utils.py:131] === Checking the job status... ===
I 03-17 22:29:52 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:29:52 utils.py:140] ==================================
I 03-17 22:30:12 utils.py:131] === Checking the job status... ===
I 03-17 22:30:13 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:30:13 utils.py:140] ==================================
I 03-17 22:30:33 utils.py:131] === Checking the job status... ===
I 03-17 22:30:34 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:30:34 utils.py:140] ==================================
I 03-17 22:30:54 utils.py:131] === Checking the job status... ===
I 03-17 22:30:55 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:30:55 utils.py:140] ==================================
I 03-17 22:31:15 utils.py:131] === Checking the job status... ===
I 03-17 22:31:16 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:31:16 utils.py:140] ==================================
I 03-17 22:31:36 utils.py:131] === Checking the job status... ===
I 03-17 22:31:37 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:31:37 utils.py:140] ==================================
I 03-17 22:31:57 utils.py:131] === Checking the job status... ===
I 03-17 22:31:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:31:58 utils.py:140] ==================================
I 03-17 22:32:18 utils.py:131] === Checking the job status... ===
I 03-17 22:32:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:32:19 utils.py:140] ==================================
I 03-17 22:32:39 utils.py:131] === Checking the job status... ===
I 03-17 22:32:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:32:40 utils.py:140] ==================================
I 03-17 22:33:00 utils.py:131] === Checking the job status... ===
I 03-17 22:33:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:33:01 utils.py:140] ==================================
I 03-17 22:33:21 utils.py:131] === Checking the job status... ===
I 03-17 22:33:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:33:22 utils.py:140] ==================================
I 03-17 22:33:42 utils.py:131] === Checking the job status... ===
I 03-17 22:33:43 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:33:43 utils.py:140] ==================================
I 03-17 22:34:03 utils.py:131] === Checking the job status... ===
I 03-17 22:34:04 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:34:04 utils.py:140] ==================================
I 03-17 22:34:24 utils.py:131] === Checking the job status... ===
I 03-17 22:34:25 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:34:25 utils.py:140] ==================================
I 03-17 22:34:45 utils.py:131] === Checking the job status... ===
I 03-17 22:34:46 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:34:46 utils.py:140] ==================================
I 03-17 22:35:06 utils.py:131] === Checking the job status... ===
I 03-17 22:35:07 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:35:07 utils.py:140] ==================================
I 03-17 22:35:27 utils.py:131] === Checking the job status... ===
I 03-17 22:35:28 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:35:28 utils.py:140] ==================================
I 03-17 22:35:48 utils.py:131] === Checking the job status... ===
I 03-17 22:35:49 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:35:49 utils.py:140] ==================================
I 03-17 22:36:09 utils.py:131] === Checking the job status... ===
I 03-17 22:36:10 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:36:10 utils.py:140] ==================================
I 03-17 22:36:30 utils.py:131] === Checking the job status... ===
I 03-17 22:36:31 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:36:31 utils.py:140] ==================================
I 03-17 22:36:51 utils.py:131] === Checking the job status... ===
I 03-17 22:36:52 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:36:52 utils.py:140] ==================================
I 03-17 22:37:12 utils.py:131] === Checking the job status... ===
I 03-17 22:37:13 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:37:13 utils.py:140] ==================================
I 03-17 22:37:33 utils.py:131] === Checking the job status... ===
I 03-17 22:37:34 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:37:34 utils.py:140] ==================================
I 03-17 22:37:54 utils.py:131] === Checking the job status... ===
I 03-17 22:37:55 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:37:55 utils.py:140] ==================================
I 03-17 22:38:15 utils.py:131] === Checking the job status... ===
I 03-17 22:38:16 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:38:16 utils.py:140] ==================================
I 03-17 22:38:36 utils.py:131] === Checking the job status... ===
I 03-17 22:38:37 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:38:37 utils.py:140] ==================================
I 03-17 22:38:57 utils.py:131] === Checking the job status... ===
I 03-17 22:38:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:38:58 utils.py:140] ==================================
I 03-17 22:39:18 utils.py:131] === Checking the job status... ===
I 03-17 22:39:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:39:19 utils.py:140] ==================================
I 03-17 22:39:39 utils.py:131] === Checking the job status... ===
I 03-17 22:39:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:39:40 utils.py:140] ==================================
I 03-17 22:40:00 utils.py:131] === Checking the job status... ===
I 03-17 22:40:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:40:01 utils.py:140] ==================================
I 03-17 22:40:21 utils.py:131] === Checking the job status... ===
I 03-17 22:40:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:40:22 utils.py:140] ==================================
I 03-17 22:40:42 utils.py:131] === Checking the job status... ===
I 03-17 22:40:43 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:40:43 utils.py:140] ==================================
I 03-17 22:41:03 utils.py:131] === Checking the job status... ===
I 03-17 22:41:04 utils.py:137] Job status: JobStatus.SUCCEEDED
I 03-17 22:41:04 utils.py:140] ==================================
I 03-17 22:41:05 state.py:561] Job succeeded.
I 03-17 22:41:05 controller.py:238] Managed job 185 (task: 0) SUCCEEDED. Cleaning up the cluster compute-text-vectors-185.
E 03-17 22:41:08 controller_utils.py:376] Failed to find the logs for the user program at ~/sky_logs/managed_jobs/sky-2025-03-17-21-19-19-321891/run.log.
I 03-17 22:41:08 controller.py:117] 
I 03-17 22:41:08 controller.py:117] == End of logs (ID: 185) ==
I 03-17 22:41:16 state.py:656] Cancellation skipped, job is already terminal
I 03-17 22:41:16 state.py:677] Cancellation skipped, job is not CANCELLING
I 03-17 22:41:18 controller.py:552] Killing controller process 65266.
I 03-17 22:41:18 controller.py:560] Controller process 65266 killed.
I 03-17 22:41:18 controller.py:562] Cleaning up any cluster for job 185.
I 03-17 22:41:18 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-eosmaz43
<sky-payload>"<rich_init>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-eosmaz43[/][/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-eosmaz43[/][/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-eosmaz43[/][/]</rich_start>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 22:41:20 storage.py:1505] [32mDeleted S3 bucket skypilot-filemounts-root-726f1974-eosmaz43.[0m
I 03-17 22:41:20 controller.py:571] Cluster of managed job 185 has been cleaned up.
