I 03-17 21:21:48 controller.py:59] DAG:
I 03-17 21:21:48 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 21:21:48 controller.py:59]   resources: {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}]
I 03-17 21:21:48 controller.py:195] Submitted managed job 292 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-21-21-48-232966_compute-text-vectors_292-0
I 03-17 21:21:48 controller.py:199] Started monitoring.
I 03-17 21:21:48 state.py:451] Launching the spot cluster...
I 03-17 21:21:48 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 21:21:49 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:21:49 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 21:21:49 optimizer.py:749] 
I 03-17 21:21:49 optimizer.py:884] Considered resources (1 node):
I 03-17 21:21:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:21:49 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:21:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:21:49 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1b   0.22       [32m   âœ”[0m     
I 03-17 21:21:49 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:21:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:21:49 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1b).
W 03-17 21:34:49 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 21:34:49 cloud_vm_ray_backend.py:2097] 
W 03-17 21:34:49 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:34:49 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:34:49 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 21:34:49 optimizer.py:749] 
I 03-17 21:34:49 optimizer.py:884] Considered resources (1 node):
I 03-17 21:34:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:34:49 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:34:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:34:49 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1a   0.25       [32m   âœ”[0m     
I 03-17 21:34:49 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:34:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:34:50 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a).
[2mW 03-17 21:40:52 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:40:53 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 21:40:53 cloud_vm_ray_backend.py:2097] 
W 03-17 21:40:53 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:40:54 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:40:54 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:40:54 optimizer.py:749] 
I 03-17 21:40:54 optimizer.py:884] Considered resources (1 node):
I 03-17 21:40:54 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:40:54 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 21:40:54 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:40:54 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2d   0.25       [32m   âœ”[0m     
I 03-17 21:40:54 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 21:40:54 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:40:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2d).
W 03-17 21:50:51 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2d for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 21:50:51 cloud_vm_ray_backend.py:2097] 
W 03-17 21:50:51 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:50:51 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:50:51 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:50:51 optimizer.py:749] 
I 03-17 21:50:51 optimizer.py:884] Considered resources (1 node):
I 03-17 21:50:51 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:50:51 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 21:50:51 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:50:51 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2a   0.27       [32m   âœ”[0m     
I 03-17 21:50:51 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 21:50:51 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:50:52 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a).
[2mW 03-17 22:00:38 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
W 03-17 22:00:40 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:00:40 cloud_vm_ray_backend.py:2097] 
W 03-17 22:00:40 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:00:40 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:00:40 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:00:40 optimizer.py:749] 
I 03-17 22:00:40 optimizer.py:884] Considered resources (1 node):
I 03-17 22:00:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:00:40 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:00:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:00:40 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1b    0.30       [32m   âœ”[0m     
I 03-17 22:00:40 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:00:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:00:40 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1b).
[2mW 03-17 22:07:36 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1c, us-east-1d.[0m
W 03-17 22:07:36 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:07:36 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:36 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:37 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:37 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:07:37 optimizer.py:749] 
I 03-17 22:07:37 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:37 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:37 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:07:37 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:37 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2c    0.31       [32m   âœ”[0m     
I 03-17 22:07:37 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:07:37 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:37 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2c).
W 03-17 22:22:11 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2c for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:22:11 cloud_vm_ray_backend.py:2097] 
W 03-17 22:22:11 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:22:12 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:22:12 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:22:12 optimizer.py:749] 
I 03-17 22:22:12 optimizer.py:884] Considered resources (1 node):
I 03-17 22:22:12 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:22:12 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:22:12 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:22:12 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2b    0.32       [32m   âœ”[0m     
I 03-17 22:22:12 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:22:12 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:22:12 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2b).
[2mW 03-17 22:25:35 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:25:36 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:25:36 cloud_vm_ray_backend.py:2097] 
W 03-17 22:25:36 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:25:36 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:25:36 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:25:36 optimizer.py:749] 
I 03-17 22:25:36 optimizer.py:884] Considered resources (1 node):
I 03-17 22:25:36 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:25:36 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:25:36 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:25:36 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1a   0.33       [32m   âœ”[0m     
I 03-17 22:25:36 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:25:36 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:25:36 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a).
[2mW 03-17 22:29:06 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:29:06 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:29:06 cloud_vm_ray_backend.py:2097] 
W 03-17 22:29:06 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:29:06 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:29:06 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:29:06 optimizer.py:749] 
I 03-17 22:29:06 optimizer.py:884] Considered resources (1 node):
I 03-17 22:29:06 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:29:06 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:29:06 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:29:06 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1c    0.34       [32m   âœ”[0m     
I 03-17 22:29:06 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:29:06 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:29:07 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1c).
[2mE 03-17 22:29:08 config.py:46] SKYPILOT_ERROR_NO_NODES_LAUNCHED: No usable subnets matching availability zone ['us-east-1c'] found. Choose a different availability zone or try manually creating an instance in your specified region to populate the list of subnets and trying this again. If you have set `use_internal_ips`, check that this zone has a subnet that (1) has the substring 'private' in its name tag and (2) does not assign public IPs (`map_public_ip_on_launch` is False).[0m
W 03-17 22:29:08 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1c for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:29:08 cloud_vm_ray_backend.py:2097] 
W 03-17 22:29:08 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:29:08 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:29:08 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:29:08 optimizer.py:749] 
I 03-17 22:29:08 optimizer.py:884] Considered resources (1 node):
I 03-17 22:29:08 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:29:08 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:29:08 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:29:08 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1b   0.34       [32m   âœ”[0m     
I 03-17 22:29:08 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:29:08 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:29:09 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1b).
[2mW 03-17 22:29:20 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:29:21 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:29:21 cloud_vm_ray_backend.py:2097] 
W 03-17 22:29:21 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:29:21 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:29:21 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:29:21 optimizer.py:749] 
I 03-17 22:29:21 optimizer.py:884] Considered resources (1 node):
I 03-17 22:29:21 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:29:21 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:29:21 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:29:21 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2a    0.34       [32m   âœ”[0m     
I 03-17 22:29:21 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:29:21 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:29:21 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2a).
[2mW 03-17 22:30:32 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:30:33 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:30:33 cloud_vm_ray_backend.py:2097] 
W 03-17 22:30:33 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:30:33 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:30:33 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:30:33 optimizer.py:749] 
I 03-17 22:30:33 optimizer.py:884] Considered resources (1 node):
I 03-17 22:30:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:30:33 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:30:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:30:33 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3c    0.35       [32m   âœ”[0m     
I 03-17 22:30:33 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:30:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:30:33 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3c).
[2mW 03-17 22:30:40 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:30:41 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3c for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:30:41 cloud_vm_ray_backend.py:2097] 
W 03-17 22:30:41 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:30:42 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:30:42 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:30:42 optimizer.py:749] 
I 03-17 22:30:42 optimizer.py:884] Considered resources (1 node):
I 03-17 22:30:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:30:42 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:30:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:30:42 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1a   0.35       [32m   âœ”[0m     
I 03-17 22:30:42 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:30:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:30:42 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a).
[2mW 03-17 22:30:52 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (eu-north-1a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-north-1b.[0m
W 03-17 22:30:53 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:30:53 cloud_vm_ray_backend.py:2097] 
W 03-17 22:30:53 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:30:53 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:30:53 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:30:53 optimizer.py:749] 
I 03-17 22:30:53 optimizer.py:884] Considered resources (1 node):
I 03-17 22:30:53 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:30:53 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:30:53 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:30:53 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2b    0.36       [32m   âœ”[0m     
I 03-17 22:30:53 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:30:53 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:30:53 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2b).
[2mW 03-17 22:31:06 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:31:07 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:31:07 cloud_vm_ray_backend.py:2097] 
W 03-17 22:31:07 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:31:07 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:31:07 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:31:07 optimizer.py:749] 
I 03-17 22:31:07 optimizer.py:884] Considered resources (1 node):
I 03-17 22:31:07 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:31:07 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:31:07 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:31:07 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2c   0.36       [32m   âœ”[0m     
I 03-17 22:31:07 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:31:07 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:31:07 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2c).
[2mW 03-17 22:31:18 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-southeast-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-southeast-2a.[0m
W 03-17 22:31:19 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-southeast-2c for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:31:19 cloud_vm_ray_backend.py:2097] 
W 03-17 22:31:19 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:31:19 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:31:19 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:31:19 optimizer.py:749] 
I 03-17 22:31:19 optimizer.py:884] Considered resources (1 node):
I 03-17 22:31:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:31:19 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:31:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:31:19 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1d    0.37       [32m   âœ”[0m     
I 03-17 22:31:19 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:31:19 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:31:19 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1d).
[2mW 03-17 22:31:26 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:31:27 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1d for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:31:27 cloud_vm_ray_backend.py:2097] 
W 03-17 22:31:27 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:31:27 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:31:27 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:31:27 optimizer.py:749] 
I 03-17 22:31:27 optimizer.py:884] Considered resources (1 node):
I 03-17 22:31:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:31:27 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:31:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:31:27 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2b    0.37       [32m   âœ”[0m     
I 03-17 22:31:27 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:31:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:31:27 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2b).
[2mW 03-17 22:43:12 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:43:13 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:43:13 cloud_vm_ray_backend.py:2097] 
W 03-17 22:43:13 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:43:13 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:43:13 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:43:13 optimizer.py:749] 
I 03-17 22:43:13 optimizer.py:884] Considered resources (1 node):
I 03-17 22:43:13 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:43:13 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:43:13 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:43:13 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1b   0.37       [32m   âœ”[0m     
I 03-17 22:43:13 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:43:13 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:43:13 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1b).
[2mW 03-17 22:43:25 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:43:25 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:43:25 cloud_vm_ray_backend.py:2097] 
W 03-17 22:43:25 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:43:25 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:43:25 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:43:25 optimizer.py:749] 
I 03-17 22:43:25 optimizer.py:884] Considered resources (1 node):
I 03-17 22:43:25 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:43:25 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:43:25 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:43:25 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2a   0.38       [32m   âœ”[0m     
I 03-17 22:43:25 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:43:25 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:43:26 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2a).
[2mW 03-17 22:43:36 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-southeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-southeast-2c.[0m
W 03-17 22:43:38 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-southeast-2a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:43:38 cloud_vm_ray_backend.py:2097] 
W 03-17 22:43:38 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:43:38 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:43:38 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:43:38 optimizer.py:749] 
I 03-17 22:43:38 optimizer.py:884] Considered resources (1 node):
I 03-17 22:43:38 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:43:38 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:43:38 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:43:38 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3b    0.38       [32m   âœ”[0m     
I 03-17 22:43:38 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:43:38 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:43:38 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3b).
[2mW 03-17 22:43:44 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (eu-west-3b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-3c.[0m
W 03-17 22:43:45 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:43:45 cloud_vm_ray_backend.py:2097] 
W 03-17 22:43:45 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:43:46 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:43:46 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:43:46 optimizer.py:749] 
I 03-17 22:43:46 optimizer.py:884] Considered resources (1 node):
I 03-17 22:43:46 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:43:46 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:43:46 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:43:46 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1a    0.39       [32m   âœ”[0m     
I 03-17 22:43:46 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:43:46 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:43:46 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1a).
[2mW 03-17 22:43:56 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:43:57 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:43:57 cloud_vm_ray_backend.py:2097] 
W 03-17 22:43:57 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:43:57 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:43:57 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:43:57 optimizer.py:749] 
I 03-17 22:43:57 optimizer.py:884] Considered resources (1 node):
I 03-17 22:43:57 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:43:57 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:43:57 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:43:57 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2a    0.40       [32m   âœ”[0m     
I 03-17 22:43:57 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:43:57 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:43:57 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2a).
[2mW 03-17 22:44:13 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:44:14 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:44:14 cloud_vm_ray_backend.py:2097] 
W 03-17 22:44:14 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:44:14 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:44:14 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:44:14 optimizer.py:749] 
I 03-17 22:44:14 optimizer.py:884] Considered resources (1 node):
I 03-17 22:44:14 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:44:14 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:44:14 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:44:14 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-central-1b   0.40       [32m   âœ”[0m     
I 03-17 22:44:14 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:44:14 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:44:14 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1b).
[2mW 03-17 22:44:24 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:44:25 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-central-1b for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:44:25 cloud_vm_ray_backend.py:2097] 
W 03-17 22:44:25 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:44:25 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:44:25 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:44:25 optimizer.py:749] 
I 03-17 22:44:25 optimizer.py:884] Considered resources (1 node):
I 03-17 22:44:25 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:44:25 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:44:25 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:44:25 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2d    0.41       [32m   âœ”[0m     
I 03-17 22:44:25 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:44:25 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:44:25 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2d).
W 03-17 22:56:43 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2d for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:56:43 cloud_vm_ray_backend.py:2097] 
W 03-17 22:56:43 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:56:43 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:56:43 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:56:43 optimizer.py:749] 
I 03-17 22:56:43 optimizer.py:884] Considered resources (1 node):
I 03-17 22:56:43 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:56:43 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:56:43 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:56:43 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-central-1a   0.41       [32m   âœ”[0m     
I 03-17 22:56:43 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:56:43 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:56:44 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1a).
[2mW 03-17 22:56:53 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:56:54 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-central-1a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 22:56:54 cloud_vm_ray_backend.py:2097] 
W 03-17 22:56:54 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:56:54 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:56:54 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:56:54 optimizer.py:749] 
I 03-17 22:56:54 optimizer.py:884] Considered resources (1 node):
I 03-17 22:56:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:54 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:56:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:54 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2c    0.41       [32m   âœ”[0m     
I 03-17 22:56:54 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:56:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:56:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2c).
[2mW 03-17 23:11:09 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 23:11:10 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2c for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:11:10 cloud_vm_ray_backend.py:2097] 
W 03-17 23:11:10 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:11:10 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:11:10 optimizer.py:749] [1mEstimated cost: [0m$0.5 / hour
I 03-17 23:11:10 optimizer.py:749] 
I 03-17 23:11:10 optimizer.py:884] Considered resources (1 node):
I 03-17 23:11:10 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 23:11:10 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 23:11:10 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 23:11:10 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-1a   0.46       [32m   âœ”[0m     
I 03-17 23:11:10 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 23:11:10 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:11:10 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-1[0m (ap-northeast-1a).
[2mW 03-17 23:11:21 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-1a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-1c.[0m
W 03-17 23:11:22 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-1a for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:11:22 cloud_vm_ray_backend.py:2097] 
W 03-17 23:11:22 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:11:22 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:11:22 optimizer.py:749] [1mEstimated cost: [0m$0.5 / hour
I 03-17 23:11:22 optimizer.py:749] 
I 03-17 23:11:22 optimizer.py:884] Considered resources (1 node):
I 03-17 23:11:22 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 23:11:22 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 23:11:22 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 23:11:22 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-1c   0.48       [32m   âœ”[0m     
I 03-17 23:11:22 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 23:11:22 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:11:22 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-1[0m (ap-northeast-1c).
[2mW 03-17 23:11:32 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-1c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-1a.[0m
W 03-17 23:11:33 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-1c for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:11:33 cloud_vm_ray_backend.py:2097] 
W 03-17 23:11:33 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:11:33 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:11:33 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 23:11:33 optimizer.py:749] 
I 03-17 23:11:33 optimizer.py:884] Considered resources (1 node):
I 03-17 23:11:33 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:11:33 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:11:33 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:11:33 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-1     0.80       [32m   âœ”[0m     
I 03-17 23:11:33 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:11:33 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:11:33 cloud_vm_ray_backend.py:2097] 
W 03-17 23:11:33 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:11:34 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:11:34 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 23:11:34 optimizer.py:749] 
I 03-17 23:11:34 optimizer.py:884] Considered resources (1 node):
I 03-17 23:11:34 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:11:34 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:11:34 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:11:34 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-2     0.80       [32m   âœ”[0m     
I 03-17 23:11:34 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:11:34 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-2 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:11:34 cloud_vm_ray_backend.py:2097] 
W 03-17 23:11:34 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:11:34 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:11:34 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 23:11:34 optimizer.py:749] 
I 03-17 23:11:34 optimizer.py:884] Considered resources (1 node):
I 03-17 23:11:34 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:11:34 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:11:34 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:11:34 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-west-2     0.80       [32m   âœ”[0m     
I 03-17 23:11:34 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:11:34 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2a).
W 03-17 23:19:46 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-west-2 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:46 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:46 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:46 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:19:46 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 23:19:46 optimizer.py:749] 
I 03-17 23:19:46 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:46 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:19:46 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:19:46 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:19:46 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-north-1    0.85       [32m   âœ”[0m     
I 03-17 23:19:46 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:46 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-north-1 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:46 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:46 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:47 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:19:47 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 23:19:47 optimizer.py:749] 
I 03-17 23:19:47 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:47 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 23:19:47 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ca-central-1   0.89       [32m   âœ”[0m     
I 03-17 23:19:47 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ca-central-1 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:47 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:19:47 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 23:19:47 optimizer.py:749] 
I 03-17 23:19:47 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-south-1    0.97       [32m   âœ”[0m     
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-south-1 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:47 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:19:47 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 23:19:47 optimizer.py:749] 
I 03-17 23:19:47 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:47 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:19:47 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 23:19:47 optimizer.py:749] 
I 03-17 23:19:47 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:47 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 23:19:47 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-central-1   1.01       [32m   âœ”[0m     
I 03-17 23:19:47 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-central-1 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:47 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:19:47 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 23:19:47 optimizer.py:749] 
I 03-17 23:19:47 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-west-2     1.02       [32m   âœ”[0m     
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-west-2 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:47 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:19:47 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 23:19:47 optimizer.py:749] 
I 03-17 23:19:47 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-west-3     1.02       [32m   âœ”[0m     
I 03-17 23:19:47 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-west-3 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:47 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:19:47 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 23:19:47 optimizer.py:749] 
I 03-17 23:19:47 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-southeast-2   1.05       [32m   âœ”[0m     
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-southeast-2 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:19:47 optimizer.py:749] [1mEstimated cost: [0m$1.2 / hour
I 03-17 23:19:47 optimizer.py:749] 
I 03-17 23:19:47 optimizer.py:884] Considered resources (1 node):
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 23:19:47 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-1   1.17       [32m   âœ”[0m     
I 03-17 23:19:47 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 23:19:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-1 for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}. 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] 
W 03-17 23:19:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 23:19:47 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-21-21-48-853138/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 23:19:47 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS([Spot], cpus=4, {'L4': 1})
I 03-17 23:19:47 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 23:19:47 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 23:19:47 recovery_strategy.py:326] Resource         Reason                                                      
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-south-1b for              
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-south-1a for              
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-northeast-2d for          
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-northeast-2a for          
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-1b for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-2c for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-2b for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ca-central-1a for            
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-1c for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ca-central-1b for            
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-west-2a for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-west-3c for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-north-1a for              
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-west-2b for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-southeast-2c for          
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-1d for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-west-2b for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-north-1b for              
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-southeast-2a for          
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-west-3b for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-1a for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-2a for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-central-1b for            
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-west-2d for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-central-1a for            
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-west-2c for {AWS([Spot],  
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.                
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-northeast-1a for          
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-northeast-1c for          
I 03-17 23:19:47 recovery_strategy.py:326] pot], {'L4':     {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] 1})                                                                          
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in us-east-1 for   
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in us-east-2 for   
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in us-west-2 for   
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in eu-north-1 for  
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ca-central-1    
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4':     
I 03-17 23:19:47 recovery_strategy.py:326]                  1})}.                                                       
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ap-south-1 for  
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ap-northeast-2  
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4':     
I 03-17 23:19:47 recovery_strategy.py:326]                  1})}.                                                       
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in eu-central-1    
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4':     
I 03-17 23:19:47 recovery_strategy.py:326]                  1})}.                                                       
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in eu-west-2 for   
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in eu-west-3 for   
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4': 1})}.   
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ap-southeast-2  
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4':     
I 03-17 23:19:47 recovery_strategy.py:326]                  1})}.                                                       
I 03-17 23:19:47 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ap-northeast-1  
I 03-17 23:19:47 recovery_strategy.py:326] {'L4': 1})       for {AWS([Spot], cpus=4, {'L4': 1}), AWS(cpus=4, {'L4':     
I 03-17 23:19:47 recovery_strategy.py:326]                  1})}.                                                       )
I 03-17 23:19:48 recovery_strategy.py:364] Retrying to launch the cluster in 51.8 seconds.
I 03-17 23:20:40 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-cnw5abbn
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 23:20:40 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:20:40 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 23:20:40 optimizer.py:749] 
I 03-17 23:20:40 optimizer.py:884] Considered resources (1 node):
I 03-17 23:20:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:20:40 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:20:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:20:40 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1b   0.22       [32m   âœ”[0m     
I 03-17 23:20:40 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 23:20:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:20:40 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1b).
[2mW 03-17 23:20:53 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 23:20:54 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 23:20:54 cloud_vm_ray_backend.py:2097] 
W 03-17 23:20:54 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:20:54 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:20:54 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 23:20:54 optimizer.py:749] 
I 03-17 23:20:54 optimizer.py:884] Considered resources (1 node):
I 03-17 23:20:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:20:54 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:20:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:20:54 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1a   0.25       [32m   âœ”[0m     
I 03-17 23:20:54 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 23:20:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:20:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a).
[2mW 03-17 23:21:07 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 23:21:08 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 23:21:08 cloud_vm_ray_backend.py:2097] 
W 03-17 23:21:08 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:21:08 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:21:08 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 23:21:08 optimizer.py:749] 
I 03-17 23:21:08 optimizer.py:884] Considered resources (1 node):
I 03-17 23:21:08 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 23:21:08 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 23:21:08 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 23:21:08 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2d   0.25       [32m   âœ”[0m     
I 03-17 23:21:08 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 23:21:08 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:21:08 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2d).
[2mW 03-17 23:21:21 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 23:21:22 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 23:21:22 cloud_vm_ray_backend.py:2097] 
W 03-17 23:21:22 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:21:23 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:21:23 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 23:21:23 optimizer.py:749] 
I 03-17 23:21:23 optimizer.py:884] Considered resources (1 node):
I 03-17 23:21:23 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 23:21:23 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 23:21:23 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 23:21:23 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2a   0.27       [32m   âœ”[0m     
I 03-17 23:21:23 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 23:21:23 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:21:23 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a).
[2mW 03-17 23:21:34 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
W 03-17 23:21:36 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 23:21:36 cloud_vm_ray_backend.py:2097] 
W 03-17 23:21:36 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:21:36 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:21:36 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 23:21:36 optimizer.py:749] 
I 03-17 23:21:36 optimizer.py:884] Considered resources (1 node):
I 03-17 23:21:36 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:21:36 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:21:36 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:21:36 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1b    0.30       [32m   âœ”[0m     
I 03-17 23:21:36 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 23:21:36 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:21:36 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1b).
[2mW 03-17 23:21:54 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 23:21:55 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 23:21:55 cloud_vm_ray_backend.py:2097] 
W 03-17 23:21:55 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:21:55 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:21:55 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 23:21:55 optimizer.py:749] 
I 03-17 23:21:55 optimizer.py:884] Considered resources (1 node):
I 03-17 23:21:55 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:21:55 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:21:55 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:21:55 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2c    0.31       [32m   âœ”[0m     
I 03-17 23:21:55 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 23:21:55 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:21:55 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2c).
[2mW 03-17 23:22:13 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-2a, us-east-2b.[0m
W 03-17 23:22:14 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 23:22:14 cloud_vm_ray_backend.py:2097] 
W 03-17 23:22:14 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:22:14 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 23:22:14 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 23:22:14 optimizer.py:749] 
I 03-17 23:22:14 optimizer.py:884] Considered resources (1 node):
I 03-17 23:22:14 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:22:14 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 23:22:14 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 23:22:14 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2b    0.32       [32m   âœ”[0m     
I 03-17 23:22:14 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 23:22:14 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:22:14 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2b).
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Waiting for SSH access[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 23:22:43 provisioner.py:451] [2mâ””â”€â”€ [0m[2mInstance is up.[0m
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (1/3 - initializing)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (2/3 - dependencies)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (3/3 - runtime)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:23:06 provisioner.py:632] [0m[32mâœ“ Cluster launched: compute-text-vectors-292.[0m  [2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 23:23:06 execution.py:332] [0mâš™ï¸Ž Syncing files.
<sky-payload>"<rich_init>[bold cyan]Syncing files[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing files[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Syncing files[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing file mounts[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/file_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:23:06 backend_utils.py:1315]   [2mSyncing (to 1 node): s3://skypilot-filemounts-root-726f1974-cnw5abbn/job-cnw5abbn/workdir -> ~/sky_workdir[0m
I 03-17 23:23:08 cloud_vm_ray_backend.py:4801] [0m[32mâœ“ Synced file_mounts.[0m  [2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/file_mounts.log[0m
<sky-payload>"<rich_update>[bold cyan]Mounting 1 storage[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/storage_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 23:23:08 backend_utils.py:1315]   [2mMounting (to 1 node): s3://sky-text-embeddings-multi-cluster-final-2 -> /output[0m
I 03-17 23:23:10 cloud_vm_ray_backend.py:4892] [0m[32mâœ“ Storage mounted.[0m  [2mView logs: sky api logs -l sky-2025-03-17-23-20-40-197980/storage_mounts.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Running setup[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Running setup[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Running setup[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
I 03-17 23:23:10 cloud_vm_ray_backend.py:3357] [0m[32mâœ“ Setup detached.[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Submitting job[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Submitting job[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Submitting job[/]</rich_start>"</sky-payload>
I 03-17 23:23:11 cloud_vm_ray_backend.py:3546] Multiple resources are specified for the task, using: AWS([Spot], cpus=4, {'L4': 1})
I 03-17 23:23:12 cloud_vm_ray_backend.py:3460] [0mâš™ï¸Ž Job submitted, ID: 1
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 23:23:12 recovery_strategy.py:289] Managed job cluster launched.
I 03-17 23:23:16 utils.py:131] === Checking the job status... ===
I 03-17 23:23:17 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:23:17 utils.py:140] ==================================
I 03-17 23:23:17 state.py:471] Job started.
I 03-17 23:23:37 utils.py:131] === Checking the job status... ===
I 03-17 23:23:38 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:23:38 utils.py:140] ==================================
I 03-17 23:23:58 utils.py:131] === Checking the job status... ===
I 03-17 23:23:59 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:23:59 utils.py:140] ==================================
I 03-17 23:24:19 utils.py:131] === Checking the job status... ===
I 03-17 23:24:20 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:24:20 utils.py:140] ==================================
I 03-17 23:24:40 utils.py:131] === Checking the job status... ===
I 03-17 23:24:40 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:24:40 utils.py:140] ==================================
I 03-17 23:25:00 utils.py:131] === Checking the job status... ===
I 03-17 23:25:01 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:25:01 utils.py:140] ==================================
I 03-17 23:25:21 utils.py:131] === Checking the job status... ===
I 03-17 23:25:22 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:25:22 utils.py:140] ==================================
I 03-17 23:25:42 utils.py:131] === Checking the job status... ===
I 03-17 23:25:43 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:25:43 utils.py:140] ==================================
I 03-17 23:26:03 utils.py:131] === Checking the job status... ===
I 03-17 23:26:04 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:26:04 utils.py:140] ==================================
I 03-17 23:26:24 utils.py:131] === Checking the job status... ===
I 03-17 23:26:24 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:26:24 utils.py:140] ==================================
I 03-17 23:26:44 utils.py:131] === Checking the job status... ===
I 03-17 23:26:45 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:26:45 utils.py:140] ==================================
I 03-17 23:27:05 utils.py:131] === Checking the job status... ===
I 03-17 23:27:06 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:27:06 utils.py:140] ==================================
I 03-17 23:27:26 utils.py:131] === Checking the job status... ===
I 03-17 23:27:27 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:27:27 utils.py:140] ==================================
I 03-17 23:27:47 utils.py:131] === Checking the job status... ===
I 03-17 23:27:48 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:27:48 utils.py:140] ==================================
I 03-17 23:28:08 utils.py:131] === Checking the job status... ===
I 03-17 23:28:09 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:28:09 utils.py:140] ==================================
I 03-17 23:28:29 utils.py:131] === Checking the job status... ===
I 03-17 23:28:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:28:29 utils.py:140] ==================================
I 03-17 23:28:50 utils.py:131] === Checking the job status... ===
I 03-17 23:28:50 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:28:50 utils.py:140] ==================================
I 03-17 23:29:10 utils.py:131] === Checking the job status... ===
I 03-17 23:29:12 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:29:12 utils.py:140] ==================================
I 03-17 23:29:32 utils.py:131] === Checking the job status... ===
I 03-17 23:29:35 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:29:35 utils.py:140] ==================================
I 03-17 23:29:55 utils.py:131] === Checking the job status... ===
I 03-17 23:29:56 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:29:56 utils.py:140] ==================================
I 03-17 23:30:16 utils.py:131] === Checking the job status... ===
I 03-17 23:30:17 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:30:17 utils.py:140] ==================================
I 03-17 23:30:37 utils.py:131] === Checking the job status... ===
I 03-17 23:30:38 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:30:38 utils.py:140] ==================================
I 03-17 23:30:58 utils.py:131] === Checking the job status... ===
I 03-17 23:30:59 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:30:59 utils.py:140] ==================================
I 03-17 23:31:19 utils.py:131] === Checking the job status... ===
I 03-17 23:31:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:31:19 utils.py:140] ==================================
I 03-17 23:31:40 utils.py:131] === Checking the job status... ===
I 03-17 23:31:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:31:40 utils.py:140] ==================================
I 03-17 23:32:00 utils.py:131] === Checking the job status... ===
I 03-17 23:32:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:32:01 utils.py:140] ==================================
I 03-17 23:32:21 utils.py:131] === Checking the job status... ===
I 03-17 23:32:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:32:22 utils.py:140] ==================================
I 03-17 23:32:42 utils.py:131] === Checking the job status... ===
I 03-17 23:32:42 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:32:42 utils.py:140] ==================================
I 03-17 23:33:03 utils.py:131] === Checking the job status... ===
I 03-17 23:33:03 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:33:03 utils.py:140] ==================================
I 03-17 23:33:23 utils.py:131] === Checking the job status... ===
I 03-17 23:33:24 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:33:24 utils.py:140] ==================================
I 03-17 23:33:44 utils.py:131] === Checking the job status... ===
I 03-17 23:33:45 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:33:45 utils.py:140] ==================================
I 03-17 23:34:05 utils.py:131] === Checking the job status... ===
I 03-17 23:34:06 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:34:06 utils.py:140] ==================================
I 03-17 23:34:26 utils.py:131] === Checking the job status... ===
I 03-17 23:34:26 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:34:26 utils.py:140] ==================================
I 03-17 23:34:46 utils.py:131] === Checking the job status... ===
I 03-17 23:34:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:34:47 utils.py:140] ==================================
I 03-17 23:35:07 utils.py:131] === Checking the job status... ===
I 03-17 23:35:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:35:08 utils.py:140] ==================================
I 03-17 23:35:28 utils.py:131] === Checking the job status... ===
I 03-17 23:35:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:35:29 utils.py:140] ==================================
I 03-17 23:35:49 utils.py:131] === Checking the job status... ===
I 03-17 23:35:49 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:35:49 utils.py:140] ==================================
I 03-17 23:36:10 utils.py:131] === Checking the job status... ===
I 03-17 23:36:10 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:36:10 utils.py:140] ==================================
I 03-17 23:36:30 utils.py:131] === Checking the job status... ===
I 03-17 23:36:31 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:36:31 utils.py:140] ==================================
I 03-17 23:36:51 utils.py:131] === Checking the job status... ===
I 03-17 23:36:52 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:36:52 utils.py:140] ==================================
I 03-17 23:37:12 utils.py:131] === Checking the job status... ===
I 03-17 23:37:13 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:37:13 utils.py:140] ==================================
I 03-17 23:37:33 utils.py:131] === Checking the job status... ===
I 03-17 23:37:33 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:37:33 utils.py:140] ==================================
I 03-17 23:37:53 utils.py:131] === Checking the job status... ===
I 03-17 23:37:54 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:37:54 utils.py:140] ==================================
I 03-17 23:38:14 utils.py:131] === Checking the job status... ===
I 03-17 23:38:15 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:38:15 utils.py:140] ==================================
I 03-17 23:38:35 utils.py:131] === Checking the job status... ===
I 03-17 23:38:36 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:38:36 utils.py:140] ==================================
I 03-17 23:38:56 utils.py:131] === Checking the job status... ===
I 03-17 23:38:56 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:38:56 utils.py:140] ==================================
I 03-17 23:39:16 utils.py:131] === Checking the job status... ===
I 03-17 23:39:17 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:39:17 utils.py:140] ==================================
I 03-17 23:39:37 utils.py:131] === Checking the job status... ===
I 03-17 23:39:38 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:39:38 utils.py:140] ==================================
I 03-17 23:39:58 utils.py:131] === Checking the job status... ===
I 03-17 23:39:59 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:39:59 utils.py:140] ==================================
I 03-17 23:40:19 utils.py:131] === Checking the job status... ===
I 03-17 23:40:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:40:19 utils.py:140] ==================================
I 03-17 23:40:39 utils.py:131] === Checking the job status... ===
I 03-17 23:40:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:40:40 utils.py:140] ==================================
I 03-17 23:41:00 utils.py:131] === Checking the job status... ===
I 03-17 23:41:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:41:01 utils.py:140] ==================================
I 03-17 23:41:21 utils.py:131] === Checking the job status... ===
I 03-17 23:41:21 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:41:21 utils.py:140] ==================================
I 03-17 23:41:42 utils.py:131] === Checking the job status... ===
I 03-17 23:41:42 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:41:42 utils.py:140] ==================================
I 03-17 23:42:02 utils.py:131] === Checking the job status... ===
I 03-17 23:42:03 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:42:03 utils.py:140] ==================================
I 03-17 23:42:23 utils.py:131] === Checking the job status... ===
I 03-17 23:42:24 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:42:24 utils.py:140] ==================================
I 03-17 23:42:44 utils.py:131] === Checking the job status... ===
I 03-17 23:42:45 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:42:45 utils.py:140] ==================================
I 03-17 23:43:05 utils.py:131] === Checking the job status... ===
I 03-17 23:43:06 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:43:06 utils.py:140] ==================================
I 03-17 23:43:26 utils.py:131] === Checking the job status... ===
I 03-17 23:43:26 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:43:26 utils.py:140] ==================================
I 03-17 23:43:46 utils.py:131] === Checking the job status... ===
I 03-17 23:43:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:43:47 utils.py:140] ==================================
I 03-17 23:44:07 utils.py:131] === Checking the job status... ===
I 03-17 23:44:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:44:08 utils.py:140] ==================================
I 03-17 23:44:28 utils.py:131] === Checking the job status... ===
I 03-17 23:44:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:44:29 utils.py:140] ==================================
I 03-17 23:44:49 utils.py:131] === Checking the job status... ===
I 03-17 23:44:49 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:44:49 utils.py:140] ==================================
I 03-17 23:45:10 utils.py:131] === Checking the job status... ===
I 03-17 23:45:10 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:45:10 utils.py:140] ==================================
I 03-17 23:45:30 utils.py:131] === Checking the job status... ===
I 03-17 23:45:31 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:45:31 utils.py:140] ==================================
I 03-17 23:45:51 utils.py:131] === Checking the job status... ===
I 03-17 23:45:52 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:45:52 utils.py:140] ==================================
I 03-17 23:46:12 utils.py:131] === Checking the job status... ===
I 03-17 23:46:13 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:46:13 utils.py:140] ==================================
I 03-17 23:46:33 utils.py:131] === Checking the job status... ===
I 03-17 23:46:33 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:46:33 utils.py:140] ==================================
I 03-17 23:46:54 utils.py:131] === Checking the job status... ===
I 03-17 23:46:54 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:46:54 utils.py:140] ==================================
I 03-17 23:47:14 utils.py:131] === Checking the job status... ===
I 03-17 23:47:15 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:47:15 utils.py:140] ==================================
