I 03-17 21:23:06 controller.py:59] DAG:
I 03-17 21:23:06 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 21:23:06 controller.py:59]   resources: {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}]
I 03-17 21:23:06 controller.py:195] Submitted managed job 350 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-21-23-06-391476_compute-text-vectors_350-0
I 03-17 21:23:06 controller.py:199] Started monitoring.
I 03-17 21:23:06 state.py:451] Launching the spot cluster...
I 03-17 21:23:06 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 21:23:07 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:23:07 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 21:23:07 optimizer.py:749] 
I 03-17 21:23:07 optimizer.py:884] Considered resources (1 node):
I 03-17 21:23:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:23:07 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:23:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:23:07 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1b   0.22       [32m   âœ”[0m     
I 03-17 21:23:07 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:23:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:23:07 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1b).
W 03-17 21:33:09 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:33:09 cloud_vm_ray_backend.py:2097] 
W 03-17 21:33:09 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:33:09 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:33:09 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 21:33:09 optimizer.py:749] 
I 03-17 21:33:09 optimizer.py:884] Considered resources (1 node):
I 03-17 21:33:09 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:33:09 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:33:09 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:33:09 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1a   0.25       [32m   âœ”[0m     
I 03-17 21:33:09 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:33:09 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:33:09 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a).
[2mW 03-17 21:40:53 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:40:54 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:40:54 cloud_vm_ray_backend.py:2097] 
W 03-17 21:40:54 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:40:55 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:40:55 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:40:55 optimizer.py:749] 
I 03-17 21:40:55 optimizer.py:884] Considered resources (1 node):
I 03-17 21:40:55 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:40:55 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 21:40:55 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:40:55 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2d   0.25       [32m   âœ”[0m     
I 03-17 21:40:55 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 21:40:55 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:40:55 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2d).
W 03-17 21:51:13 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:51:13 cloud_vm_ray_backend.py:2097] 
W 03-17 21:51:13 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:51:13 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:51:13 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:51:13 optimizer.py:749] 
I 03-17 21:51:13 optimizer.py:884] Considered resources (1 node):
I 03-17 21:51:13 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:51:13 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 21:51:13 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:51:13 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2a   0.27       [32m   âœ”[0m     
I 03-17 21:51:13 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 21:51:13 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:51:13 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a).
[2mW 03-17 21:58:25 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 21:58:27 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:58:27 cloud_vm_ray_backend.py:2097] 
W 03-17 21:58:27 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:58:27 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:58:27 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:58:27 optimizer.py:749] 
I 03-17 21:58:27 optimizer.py:884] Considered resources (1 node):
I 03-17 21:58:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:58:27 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:58:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:58:27 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1b    0.30       [32m   âœ”[0m     
I 03-17 21:58:27 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:58:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:58:27 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1b).
[2mW 03-17 22:11:07 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:11:07 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:11:07 cloud_vm_ray_backend.py:2097] 
W 03-17 22:11:07 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:11:07 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:11:07 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:11:07 optimizer.py:749] 
I 03-17 22:11:07 optimizer.py:884] Considered resources (1 node):
I 03-17 22:11:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:11:07 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:11:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:11:07 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2c    0.31       [32m   âœ”[0m     
I 03-17 22:11:07 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:11:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:11:08 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2c).
[2mW 03-17 22:16:19 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-2a, us-east-2b.[0m
W 03-17 22:16:19 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:16:19 cloud_vm_ray_backend.py:2097] 
W 03-17 22:16:19 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:16:20 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:16:20 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:16:20 optimizer.py:749] 
I 03-17 22:16:20 optimizer.py:884] Considered resources (1 node):
I 03-17 22:16:20 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:16:20 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:16:20 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:16:20 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2b    0.32       [32m   âœ”[0m     
I 03-17 22:16:20 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:16:20 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:16:20 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2b).
[2mW 03-17 22:18:24 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:18:24 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:18:24 cloud_vm_ray_backend.py:2097] 
W 03-17 22:18:24 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:18:24 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:18:24 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:18:24 optimizer.py:749] 
I 03-17 22:18:24 optimizer.py:884] Considered resources (1 node):
I 03-17 22:18:24 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:18:24 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:18:24 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:18:24 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1a   0.33       [32m   âœ”[0m     
I 03-17 22:18:24 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:18:24 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:18:24 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a).
[2mW 03-17 22:18:52 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:18:52 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:18:52 cloud_vm_ray_backend.py:2097] 
W 03-17 22:18:52 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:18:52 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:18:52 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:18:52 optimizer.py:749] 
I 03-17 22:18:52 optimizer.py:884] Considered resources (1 node):
I 03-17 22:18:52 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:18:52 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:18:52 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:18:52 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1c    0.34       [32m   âœ”[0m     
I 03-17 22:18:52 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:18:52 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:18:53 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1c).
[2mE 03-17 22:18:54 config.py:46] SKYPILOT_ERROR_NO_NODES_LAUNCHED: No usable subnets matching availability zone ['us-east-1c'] found. Choose a different availability zone or try manually creating an instance in your specified region to populate the list of subnets and trying this again. If you have set `use_internal_ips`, check that this zone has a subnet that (1) has the substring 'private' in its name tag and (2) does not assign public IPs (`map_public_ip_on_launch` is False).[0m
W 03-17 22:18:54 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:18:54 cloud_vm_ray_backend.py:2097] 
W 03-17 22:18:54 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:18:54 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:18:54 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:18:54 optimizer.py:749] 
I 03-17 22:18:54 optimizer.py:884] Considered resources (1 node):
I 03-17 22:18:54 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:18:54 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:18:54 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:18:54 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1b   0.34       [32m   âœ”[0m     
I 03-17 22:18:54 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:18:54 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:18:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1b).
[2mW 03-17 22:18:59 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:18:59 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:18:59 cloud_vm_ray_backend.py:2097] 
W 03-17 22:18:59 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:19:00 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:19:00 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:19:00 optimizer.py:749] 
I 03-17 22:19:00 optimizer.py:884] Considered resources (1 node):
I 03-17 22:19:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:00 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:19:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:00 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2a    0.34       [32m   âœ”[0m     
I 03-17 22:19:00 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:19:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:19:00 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2a).
[2mW 03-17 22:19:07 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:19:08 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:19:08 cloud_vm_ray_backend.py:2097] 
W 03-17 22:19:08 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:19:09 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:19:09 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:19:09 optimizer.py:749] 
I 03-17 22:19:09 optimizer.py:884] Considered resources (1 node):
I 03-17 22:19:09 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:09 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:19:09 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:09 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3c    0.35       [32m   âœ”[0m     
I 03-17 22:19:09 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:19:09 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:19:09 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3c).
[2mW 03-17 22:19:17 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:19:17 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:19:17 cloud_vm_ray_backend.py:2097] 
W 03-17 22:19:17 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:19:18 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:19:18 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:19:18 optimizer.py:749] 
I 03-17 22:19:18 optimizer.py:884] Considered resources (1 node):
I 03-17 22:19:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:18 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:19:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:18 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1a   0.35       [32m   âœ”[0m     
I 03-17 22:19:18 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:19:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:19:18 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a).
[2mW 03-17 22:19:29 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:19:30 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:19:30 cloud_vm_ray_backend.py:2097] 
W 03-17 22:19:30 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:19:30 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:19:30 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:19:30 optimizer.py:749] 
I 03-17 22:19:30 optimizer.py:884] Considered resources (1 node):
I 03-17 22:19:30 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:30 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:19:30 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:30 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2b    0.36       [32m   âœ”[0m     
I 03-17 22:19:30 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:19:30 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:19:31 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2b).
[2mW 03-17 22:19:38 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:19:39 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:19:39 cloud_vm_ray_backend.py:2097] 
W 03-17 22:19:39 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:19:39 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:19:39 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:19:39 optimizer.py:749] 
I 03-17 22:19:39 optimizer.py:884] Considered resources (1 node):
I 03-17 22:19:39 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:19:39 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:19:39 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:19:39 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2c   0.36       [32m   âœ”[0m     
I 03-17 22:19:39 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:19:39 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:19:39 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2c).
[2mW 03-17 22:19:50 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-southeast-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-southeast-2a.[0m
W 03-17 22:19:51 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-southeast-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:19:51 cloud_vm_ray_backend.py:2097] 
W 03-17 22:19:51 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:19:51 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:19:51 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:19:51 optimizer.py:749] 
I 03-17 22:19:51 optimizer.py:884] Considered resources (1 node):
I 03-17 22:19:51 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:51 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:19:51 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:51 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1d    0.37       [32m   âœ”[0m     
I 03-17 22:19:51 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:19:51 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:19:51 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1d).
[2mW 03-17 22:19:59 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:19:59 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:19:59 cloud_vm_ray_backend.py:2097] 
W 03-17 22:19:59 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:19:59 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:19:59 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:19:59 optimizer.py:749] 
I 03-17 22:19:59 optimizer.py:884] Considered resources (1 node):
I 03-17 22:19:59 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:59 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:19:59 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:19:59 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2b    0.37       [32m   âœ”[0m     
I 03-17 22:19:59 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:19:59 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:20:00 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2b).
[2mW 03-17 22:20:39 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-west-2b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-west-2a, us-west-2c, us-west-2d.[0m
W 03-17 22:20:40 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:20:40 cloud_vm_ray_backend.py:2097] 
W 03-17 22:20:40 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:20:40 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:20:40 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:20:40 optimizer.py:749] 
I 03-17 22:20:40 optimizer.py:884] Considered resources (1 node):
I 03-17 22:20:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:20:40 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:20:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:20:40 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1b   0.37       [32m   âœ”[0m     
I 03-17 22:20:40 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:20:40 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:20:41 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1b).
[2mW 03-17 22:20:52 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:20:53 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:20:53 cloud_vm_ray_backend.py:2097] 
W 03-17 22:20:53 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:20:53 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:20:53 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:20:53 optimizer.py:749] 
I 03-17 22:20:53 optimizer.py:884] Considered resources (1 node):
I 03-17 22:20:53 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:20:53 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:20:53 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:20:53 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2a   0.38       [32m   âœ”[0m     
I 03-17 22:20:53 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:20:53 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:20:53 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2a).
[2mW 03-17 22:21:04 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-southeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-southeast-2c.[0m
W 03-17 22:21:05 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-southeast-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:21:05 cloud_vm_ray_backend.py:2097] 
W 03-17 22:21:05 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:21:05 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:21:05 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:21:05 optimizer.py:749] 
I 03-17 22:21:05 optimizer.py:884] Considered resources (1 node):
I 03-17 22:21:05 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:21:05 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:21:05 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:21:05 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3b    0.38       [32m   âœ”[0m     
I 03-17 22:21:05 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:21:05 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:21:06 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3b).
[2mW 03-17 22:21:12 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (eu-west-3b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-3c.[0m
W 03-17 22:21:13 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:21:13 cloud_vm_ray_backend.py:2097] 
W 03-17 22:21:13 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:21:13 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:21:13 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:21:13 optimizer.py:749] 
I 03-17 22:21:13 optimizer.py:884] Considered resources (1 node):
I 03-17 22:21:13 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:21:13 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:21:13 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:21:13 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1a    0.39       [32m   âœ”[0m     
I 03-17 22:21:13 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:21:13 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:21:13 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1a).
[2mW 03-17 22:21:20 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:21:20 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:21:20 cloud_vm_ray_backend.py:2097] 
W 03-17 22:21:20 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:21:20 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:21:20 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:21:20 optimizer.py:749] 
I 03-17 22:21:20 optimizer.py:884] Considered resources (1 node):
I 03-17 22:21:20 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:21:20 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:21:20 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:21:20 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2a    0.40       [32m   âœ”[0m     
I 03-17 22:21:20 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:21:20 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:21:21 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2a).
[2mW 03-17 22:24:05 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-2b, us-east-2c.[0m
W 03-17 22:24:06 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:24:06 cloud_vm_ray_backend.py:2097] 
W 03-17 22:24:06 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:24:06 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:24:06 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:24:06 optimizer.py:749] 
I 03-17 22:24:06 optimizer.py:884] Considered resources (1 node):
I 03-17 22:24:06 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:24:06 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:24:06 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:24:06 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-central-1b   0.40       [32m   âœ”[0m     
I 03-17 22:24:06 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:24:06 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:24:06 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1b).
[2mW 03-17 22:24:34 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:24:35 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-central-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:24:35 cloud_vm_ray_backend.py:2097] 
W 03-17 22:24:35 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:24:35 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:24:35 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:24:35 optimizer.py:749] 
I 03-17 22:24:35 optimizer.py:884] Considered resources (1 node):
I 03-17 22:24:35 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:24:35 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:24:35 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:24:35 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2d    0.41       [32m   âœ”[0m     
I 03-17 22:24:35 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:24:35 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:24:35 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2d).
W 03-17 22:32:28 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:32:28 cloud_vm_ray_backend.py:2097] 
W 03-17 22:32:28 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:32:29 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:32:29 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:32:29 optimizer.py:749] 
I 03-17 22:32:29 optimizer.py:884] Considered resources (1 node):
I 03-17 22:32:29 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:32:29 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:32:29 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:32:29 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-central-1a   0.41       [32m   âœ”[0m     
I 03-17 22:32:29 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:32:29 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:32:29 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1a).
[2mW 03-17 22:32:38 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:32:39 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-central-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:32:39 cloud_vm_ray_backend.py:2097] 
W 03-17 22:32:39 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:32:39 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:32:39 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:32:39 optimizer.py:749] 
I 03-17 22:32:39 optimizer.py:884] Considered resources (1 node):
I 03-17 22:32:39 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:32:39 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:32:39 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:32:39 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2c    0.41       [32m   âœ”[0m     
I 03-17 22:32:39 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:32:39 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:32:39 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2c).
[2mW 03-17 22:46:39 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:46:40 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:46:40 cloud_vm_ray_backend.py:2097] 
W 03-17 22:46:40 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:46:40 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:46:40 optimizer.py:749] [1mEstimated cost: [0m$0.5 / hour
I 03-17 22:46:40 optimizer.py:749] 
I 03-17 22:46:40 optimizer.py:884] Considered resources (1 node):
I 03-17 22:46:40 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:46:40 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:46:40 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:46:40 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-1a   0.46       [32m   âœ”[0m     
I 03-17 22:46:40 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:46:40 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:46:40 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-1[0m (ap-northeast-1a).
[2mW 03-17 22:46:52 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:46:53 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:46:53 cloud_vm_ray_backend.py:2097] 
W 03-17 22:46:53 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:46:53 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:46:53 optimizer.py:749] [1mEstimated cost: [0m$0.5 / hour
I 03-17 22:46:53 optimizer.py:749] 
I 03-17 22:46:53 optimizer.py:884] Considered resources (1 node):
I 03-17 22:46:53 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:46:53 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:46:53 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:46:53 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-1c   0.48       [32m   âœ”[0m     
I 03-17 22:46:53 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:46:53 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:46:53 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-1[0m (ap-northeast-1c).
[2mW 03-17 22:47:11 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:47:12 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-1c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:47:12 cloud_vm_ray_backend.py:2097] 
W 03-17 22:47:12 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:47:12 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:47:12 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 22:47:12 optimizer.py:749] 
I 03-17 22:47:12 optimizer.py:884] Considered resources (1 node):
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:47:12 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:47:12 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-1     0.80       [32m   âœ”[0m     
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:47:12 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:47:12 cloud_vm_ray_backend.py:2097] 
W 03-17 22:47:12 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:47:12 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:47:12 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 22:47:12 optimizer.py:749] 
I 03-17 22:47:12 optimizer.py:884] Considered resources (1 node):
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:47:12 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:47:12 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-2     0.80       [32m   âœ”[0m     
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:47:12 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-2 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:47:12 cloud_vm_ray_backend.py:2097] 
W 03-17 22:47:12 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:47:12 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:47:12 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 22:47:12 optimizer.py:749] 
I 03-17 22:47:12 optimizer.py:884] Considered resources (1 node):
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:47:12 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:47:12 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-west-2     0.80       [32m   âœ”[0m     
I 03-17 22:47:12 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:47:12 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2a).
[2mW 03-17 22:53:27 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-west-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-west-2b, us-west-2c, us-west-2d.[0m
W 03-17 22:53:28 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-west-2 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:28 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:53:28 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 22:53:28 optimizer.py:749] 
I 03-17 22:53:28 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:28 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:53:28 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:53:28 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:53:28 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-north-1    0.85       [32m   âœ”[0m     
I 03-17 22:53:28 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:28 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-north-1 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:28 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:53:28 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 22:53:28 optimizer.py:749] 
I 03-17 22:53:28 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:28 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 22:53:28 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 22:53:28 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 22:53:28 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ca-central-1   0.89       [32m   âœ”[0m     
I 03-17 22:53:28 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:28 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ca-central-1 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:28 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:53:28 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 22:53:28 optimizer.py:749] 
I 03-17 22:53:28 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:28 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:53:28 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:53:28 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:53:28 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-south-1    0.97       [32m   âœ”[0m     
I 03-17 22:53:28 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:28 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-south-1 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:28 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:53:28 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 22:53:28 optimizer.py:749] 
I 03-17 22:53:28 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:28 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 22:53:28 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 22:53:28 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 22:53:28 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 22:53:28 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:28 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:28 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:29 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:53:29 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 22:53:29 optimizer.py:749] 
I 03-17 22:53:29 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:29 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 22:53:29 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-central-1   1.01       [32m   âœ”[0m     
I 03-17 22:53:29 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:29 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-central-1 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:29 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:53:29 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 22:53:29 optimizer.py:749] 
I 03-17 22:53:29 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:29 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:53:29 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-west-2     1.02       [32m   âœ”[0m     
I 03-17 22:53:29 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:29 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-west-2 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:29 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:53:29 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 22:53:29 optimizer.py:749] 
I 03-17 22:53:29 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:29 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:53:29 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-west-3     1.02       [32m   âœ”[0m     
I 03-17 22:53:29 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:29 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-west-3 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:29 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:53:29 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 22:53:29 optimizer.py:749] 
I 03-17 22:53:29 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:29 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 22:53:29 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-southeast-2   1.05       [32m   âœ”[0m     
I 03-17 22:53:29 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:29 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-southeast-2 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:53:29 optimizer.py:749] [1mEstimated cost: [0m$1.2 / hour
I 03-17 22:53:29 optimizer.py:749] 
I 03-17 22:53:29 optimizer.py:884] Considered resources (1 node):
I 03-17 22:53:29 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 22:53:29 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 22:53:29 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-1   1.17       [32m   âœ”[0m     
I 03-17 22:53:29 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
W 03-17 22:53:29 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-1 for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] 
W 03-17 22:53:29 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 22:53:29 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-21-23-06-993152/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 22:53:29 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 22:53:29 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 22:53:29 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 22:53:29 recovery_strategy.py:326] Resource         Reason                                                      
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-south-1b for              
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-south-1a for              
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-northeast-2d for          
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-northeast-2a for          
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-1b for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-2c for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-2b for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ca-central-1a for            
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-1c for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ca-central-1b for            
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-west-2a for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-west-3c for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-north-1a for              
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-west-2b for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-southeast-2c for          
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-1d for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-west-2b for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-north-1b for              
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-southeast-2a for          
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-west-3b for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-1a for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-east-2a for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-central-1b for            
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-west-2d for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in eu-central-1a for            
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in us-west-2c for {AWS(cpus=4,  
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.                
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-northeast-1a for          
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge[S  Failed to acquire resources in ap-northeast-1c for          
I 03-17 22:53:29 recovery_strategy.py:326] pot], {'L4':     {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] 1})                                                                          
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in us-east-1 for   
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in us-east-2 for   
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in us-west-2 for   
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in eu-north-1 for  
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ca-central-1    
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4':     
I 03-17 22:53:29 recovery_strategy.py:326]                  1})}.                                                       
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ap-south-1 for  
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ap-northeast-2  
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4':     
I 03-17 22:53:29 recovery_strategy.py:326]                  1})}.                                                       
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in eu-central-1    
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4':     
I 03-17 22:53:29 recovery_strategy.py:326]                  1})}.                                                       
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in eu-west-2 for   
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in eu-west-3 for   
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}.   
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ap-southeast-2  
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4':     
I 03-17 22:53:29 recovery_strategy.py:326]                  1})}.                                                       
I 03-17 22:53:29 recovery_strategy.py:326] AWS(g6.xlarge,   Failed to acquire resources in all zones in ap-northeast-1  
I 03-17 22:53:29 recovery_strategy.py:326] {'L4': 1})       for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4':     
I 03-17 22:53:29 recovery_strategy.py:326]                  1})}.                                                       )
I 03-17 22:53:29 recovery_strategy.py:364] Retrying to launch the cluster in 45.0 seconds.
I 03-17 22:54:15 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-28kxjtpu
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 22:54:15 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:54:15 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 22:54:15 optimizer.py:749] 
I 03-17 22:54:15 optimizer.py:884] Considered resources (1 node):
I 03-17 22:54:15 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:54:15 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:54:15 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:54:15 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1b   0.22       [32m   âœ”[0m     
I 03-17 22:54:15 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:54:15 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:54:15 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1b).
[2mW 03-17 22:54:46 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:54:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:54:47 cloud_vm_ray_backend.py:2097] 
W 03-17 22:54:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:54:48 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:54:48 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 22:54:48 optimizer.py:749] 
I 03-17 22:54:48 optimizer.py:884] Considered resources (1 node):
I 03-17 22:54:48 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:54:48 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:54:48 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:54:48 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1a   0.25       [32m   âœ”[0m     
I 03-17 22:54:48 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:54:48 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:54:48 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a).
[2mW 03-17 22:55:08 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:55:09 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:55:09 cloud_vm_ray_backend.py:2097] 
W 03-17 22:55:09 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:55:10 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:55:10 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:55:10 optimizer.py:749] 
I 03-17 22:55:10 optimizer.py:884] Considered resources (1 node):
I 03-17 22:55:10 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:55:10 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:55:10 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:55:10 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2d   0.25       [32m   âœ”[0m     
I 03-17 22:55:10 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:55:10 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:55:10 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2d).
[2mW 03-17 22:55:23 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:55:24 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:55:24 cloud_vm_ray_backend.py:2097] 
W 03-17 22:55:24 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:55:25 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:55:25 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:55:25 optimizer.py:749] 
I 03-17 22:55:25 optimizer.py:884] Considered resources (1 node):
I 03-17 22:55:25 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:55:25 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:55:25 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:55:25 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2a   0.27       [32m   âœ”[0m     
I 03-17 22:55:25 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:55:25 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:55:25 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a).
[2mW 03-17 22:55:36 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
W 03-17 22:55:38 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:55:38 cloud_vm_ray_backend.py:2097] 
W 03-17 22:55:38 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:55:38 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:55:38 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:55:38 optimizer.py:749] 
I 03-17 22:55:38 optimizer.py:884] Considered resources (1 node):
I 03-17 22:55:38 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:55:38 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:55:38 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:55:38 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1b    0.30       [32m   âœ”[0m     
I 03-17 22:55:38 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:55:38 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:55:38 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1b).
[2mW 03-17 22:55:52 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1c, us-east-1d.[0m
W 03-17 22:55:52 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:55:52 cloud_vm_ray_backend.py:2097] 
W 03-17 22:55:52 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:55:52 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:55:52 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:55:52 optimizer.py:749] 
I 03-17 22:55:52 optimizer.py:884] Considered resources (1 node):
I 03-17 22:55:52 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:55:52 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:55:52 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:55:52 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2c    0.31       [32m   âœ”[0m     
I 03-17 22:55:52 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:55:52 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:55:52 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2c).
[2mW 03-17 22:55:59 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-2a, us-east-2b.[0m
W 03-17 22:55:59 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:55:59 cloud_vm_ray_backend.py:2097] 
W 03-17 22:55:59 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:56:00 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:56:00 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:56:00 optimizer.py:749] 
I 03-17 22:56:00 optimizer.py:884] Considered resources (1 node):
I 03-17 22:56:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:00 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:56:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:00 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2b    0.32       [32m   âœ”[0m     
I 03-17 22:56:00 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:56:00 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:56:00 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2b).
[2mW 03-17 22:56:19 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:56:19 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:56:19 cloud_vm_ray_backend.py:2097] 
W 03-17 22:56:19 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:56:19 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:56:19 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:56:19 optimizer.py:749] 
I 03-17 22:56:19 optimizer.py:884] Considered resources (1 node):
I 03-17 22:56:19 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:56:19 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:56:19 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:56:19 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1a   0.33       [32m   âœ”[0m     
I 03-17 22:56:19 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:56:19 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:56:20 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a).
[2mW 03-17 22:56:31 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:56:31 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:56:31 cloud_vm_ray_backend.py:2097] 
W 03-17 22:56:31 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:56:32 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:56:32 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:56:32 optimizer.py:749] 
I 03-17 22:56:32 optimizer.py:884] Considered resources (1 node):
I 03-17 22:56:32 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:32 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:56:32 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:32 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1c    0.34       [32m   âœ”[0m     
I 03-17 22:56:32 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:56:32 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:56:32 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1c).
[2mE 03-17 22:56:33 config.py:46] SKYPILOT_ERROR_NO_NODES_LAUNCHED: No usable subnets matching availability zone ['us-east-1c'] found. Choose a different availability zone or try manually creating an instance in your specified region to populate the list of subnets and trying this again. If you have set `use_internal_ips`, check that this zone has a subnet that (1) has the substring 'private' in its name tag and (2) does not assign public IPs (`map_public_ip_on_launch` is False).[0m
W 03-17 22:56:33 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:56:33 cloud_vm_ray_backend.py:2097] 
W 03-17 22:56:33 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:56:34 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:56:34 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:56:34 optimizer.py:749] 
I 03-17 22:56:34 optimizer.py:884] Considered resources (1 node):
I 03-17 22:56:34 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:56:34 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:56:34 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:56:34 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1b   0.34       [32m   âœ”[0m     
I 03-17 22:56:34 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:56:34 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:56:34 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1b).
[2mW 03-17 22:56:45 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:56:45 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:56:45 cloud_vm_ray_backend.py:2097] 
W 03-17 22:56:45 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:56:45 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:56:45 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:56:45 optimizer.py:749] 
I 03-17 22:56:45 optimizer.py:884] Considered resources (1 node):
I 03-17 22:56:45 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:45 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:56:45 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:45 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2a    0.34       [32m   âœ”[0m     
I 03-17 22:56:45 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:56:45 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:56:45 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2a).
[2mW 03-17 22:56:53 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:56:54 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:56:54 cloud_vm_ray_backend.py:2097] 
W 03-17 22:56:54 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:56:54 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:56:54 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 22:56:54 optimizer.py:749] 
I 03-17 22:56:54 optimizer.py:884] Considered resources (1 node):
I 03-17 22:56:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:54 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:56:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:56:54 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3c    0.35       [32m   âœ”[0m     
I 03-17 22:56:54 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:56:54 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:56:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3c).
[2mW 03-17 22:57:01 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:57:02 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:57:02 cloud_vm_ray_backend.py:2097] 
W 03-17 22:57:02 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:57:02 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:57:02 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:57:02 optimizer.py:749] 
I 03-17 22:57:02 optimizer.py:884] Considered resources (1 node):
I 03-17 22:57:02 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:57:02 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:57:02 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:57:02 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1a   0.35       [32m   âœ”[0m     
I 03-17 22:57:02 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:57:02 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:57:02 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a).
[2mW 03-17 22:57:14 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:57:15 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:57:15 cloud_vm_ray_backend.py:2097] 
W 03-17 22:57:15 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:57:15 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:57:15 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:57:15 optimizer.py:749] 
I 03-17 22:57:15 optimizer.py:884] Considered resources (1 node):
I 03-17 22:57:15 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:57:15 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:57:15 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:57:15 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2b    0.36       [32m   âœ”[0m     
I 03-17 22:57:15 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:57:15 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:57:15 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2b).
[2mW 03-17 22:57:22 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:57:23 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:57:23 cloud_vm_ray_backend.py:2097] 
W 03-17 22:57:23 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:57:23 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:57:23 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:57:23 optimizer.py:749] 
I 03-17 22:57:23 optimizer.py:884] Considered resources (1 node):
I 03-17 22:57:23 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:57:23 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:57:23 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:57:23 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2c   0.36       [32m   âœ”[0m     
I 03-17 22:57:23 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:57:23 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:57:23 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2c).
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Waiting for SSH access[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:57:51 provisioner.py:451] [2mâ””â”€â”€ [0m[2mInstance is up.[0m
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (1/3 - initializing)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (2/3 - dependencies)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (3/3 - runtime)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:58:22 provisioner.py:632] [0m[32mâœ“ Cluster launched: compute-text-vectors-350.[0m  [2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 22:58:22 execution.py:332] [0mâš™ï¸Ž Syncing files.
<sky-payload>"<rich_init>[bold cyan]Syncing files[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing files[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Syncing files[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing file mounts[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/file_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:58:23 backend_utils.py:1315]   [2mSyncing (to 1 node): s3://skypilot-filemounts-root-726f1974-28kxjtpu/job-28kxjtpu/workdir -> ~/sky_workdir[0m
I 03-17 22:58:26 cloud_vm_ray_backend.py:4801] [0m[32mâœ“ Synced file_mounts.[0m  [2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/file_mounts.log[0m
<sky-payload>"<rich_update>[bold cyan]Mounting 1 storage[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/storage_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:58:26 backend_utils.py:1315]   [2mMounting (to 1 node): s3://sky-text-embeddings-multi-cluster-final-2 -> /output[0m
I 03-17 22:58:30 cloud_vm_ray_backend.py:4892] [0m[32mâœ“ Storage mounted.[0m  [2mView logs: sky api logs -l sky-2025-03-17-22-54-15-168035/storage_mounts.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Running setup[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Running setup[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Running setup[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
I 03-17 22:58:34 cloud_vm_ray_backend.py:3357] [0m[32mâœ“ Setup detached.[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Submitting job[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Submitting job[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Submitting job[/]</rich_start>"</sky-payload>
I 03-17 22:58:35 cloud_vm_ray_backend.py:3546] Multiple resources are specified for the task, using: AWS([Spot], cpus=4, {'L4': 1})
I 03-17 22:58:37 cloud_vm_ray_backend.py:3460] [0mâš™ï¸Ž Job submitted, ID: 1
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 22:58:37 recovery_strategy.py:289] Managed job cluster launched.
I 03-17 22:58:41 utils.py:131] === Checking the job status... ===
I 03-17 22:58:42 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:58:42 utils.py:140] ==================================
I 03-17 22:58:43 state.py:471] Job started.
I 03-17 22:59:04 utils.py:131] === Checking the job status... ===
I 03-17 22:59:05 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:59:05 utils.py:140] ==================================
I 03-17 22:59:25 utils.py:131] === Checking the job status... ===
I 03-17 22:59:26 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:59:26 utils.py:140] ==================================
I 03-17 22:59:46 utils.py:131] === Checking the job status... ===
I 03-17 22:59:47 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:59:47 utils.py:140] ==================================
I 03-17 23:00:07 utils.py:131] === Checking the job status... ===
I 03-17 23:00:08 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:00:08 utils.py:140] ==================================
I 03-17 23:00:28 utils.py:131] === Checking the job status... ===
I 03-17 23:00:29 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 23:00:29 utils.py:140] ==================================
I 03-17 23:00:49 utils.py:131] === Checking the job status... ===
I 03-17 23:00:51 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:00:51 utils.py:140] ==================================
I 03-17 23:01:11 utils.py:131] === Checking the job status... ===
I 03-17 23:01:12 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:01:12 utils.py:140] ==================================
I 03-17 23:01:32 utils.py:131] === Checking the job status... ===
I 03-17 23:01:33 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:01:33 utils.py:140] ==================================
I 03-17 23:01:53 utils.py:131] === Checking the job status... ===
I 03-17 23:01:54 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:01:54 utils.py:140] ==================================
I 03-17 23:02:15 utils.py:131] === Checking the job status... ===
I 03-17 23:02:16 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:02:16 utils.py:140] ==================================
I 03-17 23:02:36 utils.py:131] === Checking the job status... ===
I 03-17 23:02:37 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:02:37 utils.py:140] ==================================
I 03-17 23:02:57 utils.py:131] === Checking the job status... ===
I 03-17 23:02:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:02:58 utils.py:140] ==================================
I 03-17 23:03:18 utils.py:131] === Checking the job status... ===
I 03-17 23:03:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:03:19 utils.py:140] ==================================
I 03-17 23:03:40 utils.py:131] === Checking the job status... ===
I 03-17 23:03:41 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:03:41 utils.py:140] ==================================
I 03-17 23:04:01 utils.py:131] === Checking the job status... ===
I 03-17 23:04:02 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:04:02 utils.py:140] ==================================
I 03-17 23:04:22 utils.py:131] === Checking the job status... ===
I 03-17 23:04:23 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:04:23 utils.py:140] ==================================
I 03-17 23:04:43 utils.py:131] === Checking the job status... ===
I 03-17 23:04:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:04:47 utils.py:140] ==================================
I 03-17 23:05:07 utils.py:131] === Checking the job status... ===
I 03-17 23:05:11 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:05:11 utils.py:140] ==================================
I 03-17 23:05:31 utils.py:131] === Checking the job status... ===
I 03-17 23:05:32 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:05:32 utils.py:140] ==================================
I 03-17 23:05:52 utils.py:131] === Checking the job status... ===
I 03-17 23:05:53 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:05:53 utils.py:140] ==================================
I 03-17 23:06:14 utils.py:131] === Checking the job status... ===
I 03-17 23:06:15 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:06:15 utils.py:140] ==================================
I 03-17 23:06:35 utils.py:131] === Checking the job status... ===
I 03-17 23:06:36 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:06:36 utils.py:140] ==================================
I 03-17 23:06:56 utils.py:131] === Checking the job status... ===
I 03-17 23:06:57 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:06:57 utils.py:140] ==================================
I 03-17 23:07:17 utils.py:131] === Checking the job status... ===
I 03-17 23:07:18 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:07:18 utils.py:140] ==================================
I 03-17 23:07:38 utils.py:131] === Checking the job status... ===
I 03-17 23:07:39 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:07:39 utils.py:140] ==================================
I 03-17 23:07:59 utils.py:131] === Checking the job status... ===
I 03-17 23:08:00 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:08:00 utils.py:140] ==================================
I 03-17 23:08:20 utils.py:131] === Checking the job status... ===
I 03-17 23:08:21 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:08:21 utils.py:140] ==================================
I 03-17 23:08:41 utils.py:131] === Checking the job status... ===
I 03-17 23:08:42 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:08:42 utils.py:140] ==================================
I 03-17 23:09:02 utils.py:131] === Checking the job status... ===
I 03-17 23:09:03 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:09:03 utils.py:140] ==================================
I 03-17 23:09:23 utils.py:131] === Checking the job status... ===
I 03-17 23:09:24 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:09:24 utils.py:140] ==================================
I 03-17 23:09:45 utils.py:131] === Checking the job status... ===
I 03-17 23:09:46 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:09:46 utils.py:140] ==================================
I 03-17 23:10:06 utils.py:131] === Checking the job status... ===
I 03-17 23:10:07 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:10:07 utils.py:140] ==================================
I 03-17 23:10:27 utils.py:131] === Checking the job status... ===
I 03-17 23:10:28 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:10:28 utils.py:140] ==================================
I 03-17 23:10:48 utils.py:131] === Checking the job status... ===
I 03-17 23:10:49 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:10:49 utils.py:140] ==================================
I 03-17 23:11:09 utils.py:131] === Checking the job status... ===
I 03-17 23:11:10 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:11:10 utils.py:140] ==================================
I 03-17 23:11:30 utils.py:131] === Checking the job status... ===
I 03-17 23:11:31 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:11:31 utils.py:140] ==================================
I 03-17 23:11:51 utils.py:131] === Checking the job status... ===
I 03-17 23:11:52 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:11:52 utils.py:140] ==================================
I 03-17 23:12:12 utils.py:131] === Checking the job status... ===
I 03-17 23:12:13 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:12:13 utils.py:140] ==================================
I 03-17 23:12:34 utils.py:131] === Checking the job status... ===
I 03-17 23:12:35 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:12:35 utils.py:140] ==================================
I 03-17 23:12:55 utils.py:131] === Checking the job status... ===
I 03-17 23:12:56 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:12:56 utils.py:140] ==================================
I 03-17 23:13:16 utils.py:131] === Checking the job status... ===
I 03-17 23:13:17 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:13:17 utils.py:140] ==================================
I 03-17 23:13:37 utils.py:131] === Checking the job status... ===
I 03-17 23:13:38 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:13:38 utils.py:140] ==================================
I 03-17 23:13:58 utils.py:131] === Checking the job status... ===
I 03-17 23:13:59 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:13:59 utils.py:140] ==================================
I 03-17 23:14:19 utils.py:131] === Checking the job status... ===
I 03-17 23:14:20 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:14:20 utils.py:140] ==================================
I 03-17 23:14:40 utils.py:131] === Checking the job status... ===
I 03-17 23:14:41 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:14:41 utils.py:140] ==================================
I 03-17 23:15:01 utils.py:131] === Checking the job status... ===
I 03-17 23:15:02 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:15:02 utils.py:140] ==================================
I 03-17 23:15:22 utils.py:131] === Checking the job status... ===
I 03-17 23:15:23 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:15:23 utils.py:140] ==================================
I 03-17 23:15:44 utils.py:131] === Checking the job status... ===
I 03-17 23:15:45 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:15:45 utils.py:140] ==================================
I 03-17 23:16:05 utils.py:131] === Checking the job status... ===
I 03-17 23:16:06 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:16:06 utils.py:140] ==================================
I 03-17 23:16:26 utils.py:131] === Checking the job status... ===
I 03-17 23:16:27 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:16:27 utils.py:140] ==================================
I 03-17 23:16:47 utils.py:131] === Checking the job status... ===
I 03-17 23:16:48 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:16:48 utils.py:140] ==================================
I 03-17 23:17:08 utils.py:131] === Checking the job status... ===
I 03-17 23:17:09 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:17:09 utils.py:140] ==================================
I 03-17 23:17:29 utils.py:131] === Checking the job status... ===
I 03-17 23:17:30 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:17:30 utils.py:140] ==================================
I 03-17 23:17:50 utils.py:131] === Checking the job status... ===
I 03-17 23:17:51 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:17:51 utils.py:140] ==================================
I 03-17 23:18:11 utils.py:131] === Checking the job status... ===
I 03-17 23:18:12 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:18:12 utils.py:140] ==================================
I 03-17 23:18:32 utils.py:131] === Checking the job status... ===
I 03-17 23:18:33 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:18:33 utils.py:140] ==================================
I 03-17 23:18:54 utils.py:131] === Checking the job status... ===
I 03-17 23:18:55 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:18:55 utils.py:140] ==================================
I 03-17 23:19:15 utils.py:131] === Checking the job status... ===
I 03-17 23:19:16 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:19:16 utils.py:140] ==================================
I 03-17 23:19:36 utils.py:131] === Checking the job status... ===
I 03-17 23:19:37 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:19:37 utils.py:140] ==================================
I 03-17 23:19:57 utils.py:131] === Checking the job status... ===
I 03-17 23:19:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:19:58 utils.py:140] ==================================
I 03-17 23:20:18 utils.py:131] === Checking the job status... ===
I 03-17 23:20:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:20:19 utils.py:140] ==================================
I 03-17 23:20:39 utils.py:131] === Checking the job status... ===
I 03-17 23:20:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:20:40 utils.py:140] ==================================
I 03-17 23:21:00 utils.py:131] === Checking the job status... ===
I 03-17 23:21:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:21:01 utils.py:140] ==================================
I 03-17 23:21:21 utils.py:131] === Checking the job status... ===
I 03-17 23:21:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:21:22 utils.py:140] ==================================
I 03-17 23:21:43 utils.py:131] === Checking the job status... ===
I 03-17 23:21:44 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:21:44 utils.py:140] ==================================
I 03-17 23:22:04 utils.py:131] === Checking the job status... ===
I 03-17 23:22:05 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:22:05 utils.py:140] ==================================
I 03-17 23:22:25 utils.py:131] === Checking the job status... ===
I 03-17 23:22:26 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:22:26 utils.py:140] ==================================
I 03-17 23:22:46 utils.py:131] === Checking the job status... ===
I 03-17 23:22:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:22:47 utils.py:140] ==================================
I 03-17 23:23:07 utils.py:131] === Checking the job status... ===
I 03-17 23:23:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:23:08 utils.py:140] ==================================
I 03-17 23:23:28 utils.py:131] === Checking the job status... ===
I 03-17 23:23:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:23:29 utils.py:140] ==================================
I 03-17 23:23:49 utils.py:131] === Checking the job status... ===
I 03-17 23:23:50 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:23:50 utils.py:140] ==================================
I 03-17 23:24:10 utils.py:131] === Checking the job status... ===
I 03-17 23:24:11 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:24:11 utils.py:140] ==================================
I 03-17 23:24:31 utils.py:131] === Checking the job status... ===
I 03-17 23:24:32 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:24:32 utils.py:140] ==================================
I 03-17 23:24:52 utils.py:131] === Checking the job status... ===
I 03-17 23:24:53 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:24:53 utils.py:140] ==================================
I 03-17 23:25:14 utils.py:131] === Checking the job status... ===
I 03-17 23:25:15 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:25:15 utils.py:140] ==================================
I 03-17 23:25:35 utils.py:131] === Checking the job status... ===
I 03-17 23:25:36 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:25:36 utils.py:140] ==================================
I 03-17 23:25:56 utils.py:131] === Checking the job status... ===
I 03-17 23:25:57 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:25:57 utils.py:140] ==================================
I 03-17 23:26:17 utils.py:131] === Checking the job status... ===
I 03-17 23:26:18 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:26:18 utils.py:140] ==================================
I 03-17 23:26:38 utils.py:131] === Checking the job status... ===
I 03-17 23:26:39 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:26:39 utils.py:140] ==================================
I 03-17 23:26:59 utils.py:131] === Checking the job status... ===
I 03-17 23:27:00 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:27:00 utils.py:140] ==================================
I 03-17 23:27:20 utils.py:131] === Checking the job status... ===
I 03-17 23:27:21 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:27:21 utils.py:140] ==================================
I 03-17 23:27:41 utils.py:131] === Checking the job status... ===
I 03-17 23:27:42 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:27:42 utils.py:140] ==================================
I 03-17 23:28:02 utils.py:131] === Checking the job status... ===
I 03-17 23:28:03 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:28:03 utils.py:140] ==================================
I 03-17 23:28:24 utils.py:131] === Checking the job status... ===
I 03-17 23:28:25 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:28:25 utils.py:140] ==================================
I 03-17 23:28:45 utils.py:131] === Checking the job status... ===
I 03-17 23:28:46 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:28:46 utils.py:140] ==================================
I 03-17 23:29:06 utils.py:131] === Checking the job status... ===
I 03-17 23:29:07 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:29:07 utils.py:140] ==================================
I 03-17 23:29:27 utils.py:131] === Checking the job status... ===
I 03-17 23:29:28 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:29:28 utils.py:140] ==================================
I 03-17 23:29:48 utils.py:131] === Checking the job status... ===
I 03-17 23:29:49 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:29:49 utils.py:140] ==================================
I 03-17 23:30:09 utils.py:131] === Checking the job status... ===
I 03-17 23:30:10 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:30:10 utils.py:140] ==================================
I 03-17 23:30:30 utils.py:131] === Checking the job status... ===
I 03-17 23:30:31 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:30:31 utils.py:140] ==================================
I 03-17 23:30:51 utils.py:131] === Checking the job status... ===
I 03-17 23:30:52 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:30:52 utils.py:140] ==================================
I 03-17 23:31:12 utils.py:131] === Checking the job status... ===
I 03-17 23:31:13 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:31:13 utils.py:140] ==================================
I 03-17 23:31:34 utils.py:131] === Checking the job status... ===
I 03-17 23:31:35 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:31:35 utils.py:140] ==================================
I 03-17 23:31:55 utils.py:131] === Checking the job status... ===
I 03-17 23:31:56 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:31:56 utils.py:140] ==================================
I 03-17 23:32:16 utils.py:131] === Checking the job status... ===
I 03-17 23:32:17 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:32:17 utils.py:140] ==================================
I 03-17 23:32:37 utils.py:131] === Checking the job status... ===
I 03-17 23:32:38 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:32:38 utils.py:140] ==================================
I 03-17 23:32:58 utils.py:131] === Checking the job status... ===
I 03-17 23:32:59 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:32:59 utils.py:140] ==================================
I 03-17 23:33:19 utils.py:131] === Checking the job status... ===
I 03-17 23:33:20 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:33:20 utils.py:140] ==================================
I 03-17 23:33:40 utils.py:131] === Checking the job status... ===
I 03-17 23:33:41 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:33:41 utils.py:140] ==================================
I 03-17 23:34:01 utils.py:131] === Checking the job status... ===
I 03-17 23:34:02 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:34:02 utils.py:140] ==================================
I 03-17 23:34:22 utils.py:131] === Checking the job status... ===
I 03-17 23:34:23 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:34:23 utils.py:140] ==================================
I 03-17 23:34:43 utils.py:131] === Checking the job status... ===
I 03-17 23:34:44 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:34:44 utils.py:140] ==================================
I 03-17 23:35:04 utils.py:131] === Checking the job status... ===
I 03-17 23:35:05 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:35:05 utils.py:140] ==================================
I 03-17 23:35:26 utils.py:131] === Checking the job status... ===
I 03-17 23:35:27 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:35:27 utils.py:140] ==================================
I 03-17 23:35:47 utils.py:131] === Checking the job status... ===
I 03-17 23:35:48 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:35:48 utils.py:140] ==================================
I 03-17 23:36:08 utils.py:131] === Checking the job status... ===
I 03-17 23:36:09 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:36:09 utils.py:140] ==================================
I 03-17 23:36:29 utils.py:131] === Checking the job status... ===
I 03-17 23:36:30 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:36:30 utils.py:140] ==================================
I 03-17 23:36:50 utils.py:131] === Checking the job status... ===
I 03-17 23:36:51 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:36:51 utils.py:140] ==================================
I 03-17 23:37:11 utils.py:131] === Checking the job status... ===
I 03-17 23:37:12 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:37:12 utils.py:140] ==================================
I 03-17 23:37:32 utils.py:131] === Checking the job status... ===
I 03-17 23:37:33 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:37:33 utils.py:140] ==================================
I 03-17 23:37:53 utils.py:131] === Checking the job status... ===
I 03-17 23:37:54 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:37:54 utils.py:140] ==================================
I 03-17 23:38:14 utils.py:131] === Checking the job status... ===
I 03-17 23:38:15 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:38:15 utils.py:140] ==================================
I 03-17 23:38:35 utils.py:131] === Checking the job status... ===
I 03-17 23:38:36 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:38:36 utils.py:140] ==================================
I 03-17 23:38:57 utils.py:131] === Checking the job status... ===
I 03-17 23:38:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:38:58 utils.py:140] ==================================
I 03-17 23:39:18 utils.py:131] === Checking the job status... ===
I 03-17 23:39:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:39:19 utils.py:140] ==================================
I 03-17 23:39:39 utils.py:131] === Checking the job status... ===
I 03-17 23:39:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:39:40 utils.py:140] ==================================
I 03-17 23:40:00 utils.py:131] === Checking the job status... ===
I 03-17 23:40:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:40:01 utils.py:140] ==================================
I 03-17 23:40:21 utils.py:131] === Checking the job status... ===
I 03-17 23:40:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:40:22 utils.py:140] ==================================
I 03-17 23:40:42 utils.py:131] === Checking the job status... ===
I 03-17 23:40:43 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:40:43 utils.py:140] ==================================
I 03-17 23:41:03 utils.py:131] === Checking the job status... ===
I 03-17 23:41:04 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:41:04 utils.py:140] ==================================
I 03-17 23:41:24 utils.py:131] === Checking the job status... ===
I 03-17 23:41:25 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:41:25 utils.py:140] ==================================
I 03-17 23:41:46 utils.py:131] === Checking the job status... ===
I 03-17 23:41:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:41:47 utils.py:140] ==================================
I 03-17 23:42:07 utils.py:131] === Checking the job status... ===
I 03-17 23:42:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:42:08 utils.py:140] ==================================
I 03-17 23:42:28 utils.py:131] === Checking the job status... ===
I 03-17 23:42:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:42:29 utils.py:140] ==================================
I 03-17 23:42:49 utils.py:131] === Checking the job status... ===
I 03-17 23:42:50 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:42:50 utils.py:140] ==================================
I 03-17 23:43:10 utils.py:131] === Checking the job status... ===
I 03-17 23:43:11 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:43:11 utils.py:140] ==================================
I 03-17 23:43:31 utils.py:131] === Checking the job status... ===
I 03-17 23:43:32 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:43:32 utils.py:140] ==================================
I 03-17 23:43:52 utils.py:131] === Checking the job status... ===
I 03-17 23:43:53 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:43:53 utils.py:140] ==================================
I 03-17 23:44:13 utils.py:131] === Checking the job status... ===
I 03-17 23:44:14 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:44:14 utils.py:140] ==================================
I 03-17 23:44:34 utils.py:131] === Checking the job status... ===
I 03-17 23:44:35 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:44:35 utils.py:140] ==================================
I 03-17 23:44:56 utils.py:131] === Checking the job status... ===
I 03-17 23:44:57 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:44:57 utils.py:140] ==================================
I 03-17 23:45:17 utils.py:131] === Checking the job status... ===
I 03-17 23:45:18 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:45:18 utils.py:140] ==================================
I 03-17 23:45:38 utils.py:131] === Checking the job status... ===
I 03-17 23:45:39 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:45:39 utils.py:140] ==================================
I 03-17 23:45:59 utils.py:131] === Checking the job status... ===
I 03-17 23:46:00 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:46:00 utils.py:140] ==================================
I 03-17 23:46:20 utils.py:131] === Checking the job status... ===
I 03-17 23:46:21 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:46:21 utils.py:140] ==================================
I 03-17 23:46:41 utils.py:131] === Checking the job status... ===
I 03-17 23:46:42 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 23:46:42 utils.py:140] ==================================
