I 03-17 21:16:47 controller.py:59] DAG:
I 03-17 21:16:47 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 21:16:47 controller.py:59]   resources: {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}]
I 03-17 21:16:47 controller.py:195] Submitted managed job 75 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-21-16-47-315444_compute-text-vectors_75-0
I 03-17 21:16:47 controller.py:199] Started monitoring.
I 03-17 21:16:47 state.py:451] Launching the spot cluster...
I 03-17 21:16:47 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 21:16:48 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:16:48 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 21:16:48 optimizer.py:749] 
I 03-17 21:16:48 optimizer.py:884] Considered resources (1 node):
I 03-17 21:16:48 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:16:48 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:16:48 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:16:48 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1b   0.22       [32m   âœ”[0m     
I 03-17 21:16:48 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:16:48 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:16:48 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1b).
[2mW 03-17 21:17:31 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-south-1b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-south-1a.[0m
W 03-17 21:17:32 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:17:32 cloud_vm_ray_backend.py:2097] 
W 03-17 21:17:32 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:17:33 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:17:33 optimizer.py:749] [1mEstimated cost: [0m$0.2 / hour
I 03-17 21:17:33 optimizer.py:749] 
I 03-17 21:17:33 optimizer.py:884] Considered resources (1 node):
I 03-17 21:17:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:17:33 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:17:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:17:33 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-south-1a   0.25       [32m   âœ”[0m     
I 03-17 21:17:33 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:17:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:17:33 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a).
[2mW 03-17 21:39:42 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:39:43 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-south-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:39:43 cloud_vm_ray_backend.py:2097] 
W 03-17 21:39:43 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:39:44 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:39:44 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:39:44 optimizer.py:749] 
I 03-17 21:39:44 optimizer.py:884] Considered resources (1 node):
I 03-17 21:39:44 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:39:44 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 21:39:44 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:39:44 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2d   0.25       [32m   âœ”[0m     
I 03-17 21:39:44 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 21:39:44 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:39:44 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2d).
[2mW 03-17 21:47:03 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 21:47:04 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:47:04 cloud_vm_ray_backend.py:2097] 
W 03-17 21:47:04 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:47:05 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:47:05 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:47:05 optimizer.py:749] 
I 03-17 21:47:05 optimizer.py:884] Considered resources (1 node):
I 03-17 21:47:05 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:47:05 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 21:47:05 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 21:47:05 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-2a   0.27       [32m   âœ”[0m     
I 03-17 21:47:05 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 21:47:05 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:47:05 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a).
[2mW 03-17 21:56:26 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
W 03-17 21:56:27 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-northeast-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:56:27 cloud_vm_ray_backend.py:2097] 
W 03-17 21:56:27 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:56:27 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:56:27 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:56:27 optimizer.py:749] 
I 03-17 21:56:27 optimizer.py:884] Considered resources (1 node):
I 03-17 21:56:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:56:27 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:56:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:56:27 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1b    0.30       [32m   âœ”[0m     
I 03-17 21:56:27 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:56:27 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:56:27 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1b).
[2mW 03-17 21:59:20 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1c, us-east-1d.[0m
W 03-17 21:59:21 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:59:21 cloud_vm_ray_backend.py:2097] 
W 03-17 21:59:21 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:59:21 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:59:21 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:59:21 optimizer.py:749] 
I 03-17 21:59:21 optimizer.py:884] Considered resources (1 node):
I 03-17 21:59:21 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:21 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:59:21 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:21 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2c    0.31       [32m   âœ”[0m     
I 03-17 21:59:21 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:59:21 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:59:21 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2c).
[2mW 03-17 21:59:28 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (us-east-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-2a, us-east-2b.[0m
W 03-17 21:59:28 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:59:28 cloud_vm_ray_backend.py:2097] 
W 03-17 21:59:28 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:59:28 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:59:28 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:59:28 optimizer.py:749] 
I 03-17 21:59:28 optimizer.py:884] Considered resources (1 node):
I 03-17 21:59:28 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:28 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:59:28 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:28 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2b    0.32       [32m   âœ”[0m     
I 03-17 21:59:28 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:59:28 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:59:29 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2b).
[2mW 03-17 21:59:35 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:59:36 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:59:36 cloud_vm_ray_backend.py:2097] 
W 03-17 21:59:36 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:59:36 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:59:36 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:59:36 optimizer.py:749] 
I 03-17 21:59:36 optimizer.py:884] Considered resources (1 node):
I 03-17 21:59:36 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 21:59:36 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 21:59:36 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 21:59:36 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1a   0.33       [32m   âœ”[0m     
I 03-17 21:59:36 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 21:59:36 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:59:36 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a).
[2mW 03-17 21:59:41 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:59:41 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:59:41 cloud_vm_ray_backend.py:2097] 
W 03-17 21:59:41 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:59:42 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:59:42 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:59:42 optimizer.py:749] 
I 03-17 21:59:42 optimizer.py:884] Considered resources (1 node):
I 03-17 21:59:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:42 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:59:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:42 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1c    0.34       [32m   âœ”[0m     
I 03-17 21:59:42 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:59:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:59:42 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1c).
[2mE 03-17 21:59:43 config.py:46] SKYPILOT_ERROR_NO_NODES_LAUNCHED: No usable subnets matching availability zone ['us-east-1c'] found. Choose a different availability zone or try manually creating an instance in your specified region to populate the list of subnets and trying this again. If you have set `use_internal_ips`, check that this zone has a subnet that (1) has the substring 'private' in its name tag and (2) does not assign public IPs (`map_public_ip_on_launch` is False).[0m
W 03-17 21:59:43 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:59:43 cloud_vm_ray_backend.py:2097] 
W 03-17 21:59:43 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:59:43 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:59:43 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:59:43 optimizer.py:749] 
I 03-17 21:59:43 optimizer.py:884] Considered resources (1 node):
I 03-17 21:59:43 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 21:59:43 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 21:59:43 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 21:59:43 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ca-central-1b   0.34       [32m   âœ”[0m     
I 03-17 21:59:43 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 21:59:43 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:59:43 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1b).
[2mW 03-17 21:59:48 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:59:49 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ca-central-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:59:49 cloud_vm_ray_backend.py:2097] 
W 03-17 21:59:49 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:59:49 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:59:49 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:59:49 optimizer.py:749] 
I 03-17 21:59:49 optimizer.py:884] Considered resources (1 node):
I 03-17 21:59:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:49 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:59:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:49 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2a    0.34       [32m   âœ”[0m     
I 03-17 21:59:49 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:59:49 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:59:49 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2a).
[2mW 03-17 21:59:56 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 21:59:57 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 21:59:57 cloud_vm_ray_backend.py:2097] 
W 03-17 21:59:57 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 21:59:57 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 21:59:57 optimizer.py:749] [1mEstimated cost: [0m$0.3 / hour
I 03-17 21:59:57 optimizer.py:749] 
I 03-17 21:59:57 optimizer.py:884] Considered resources (1 node):
I 03-17 21:59:57 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:57 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 21:59:57 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 21:59:57 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3c    0.35       [32m   âœ”[0m     
I 03-17 21:59:57 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 21:59:57 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 21:59:57 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3c).
[2mW 03-17 22:00:04 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (eu-west-3c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-3b.[0m
W 03-17 22:00:05 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:00:05 cloud_vm_ray_backend.py:2097] 
W 03-17 22:00:05 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:00:05 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:00:05 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:00:05 optimizer.py:749] 
I 03-17 22:00:05 optimizer.py:884] Considered resources (1 node):
I 03-17 22:00:05 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:00:05 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:00:05 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:00:05 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1a   0.35       [32m   âœ”[0m     
I 03-17 22:00:05 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:00:05 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:00:06 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a).
[2mW 03-17 22:00:17 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:00:18 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:00:18 cloud_vm_ray_backend.py:2097] 
W 03-17 22:00:18 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:00:18 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:00:18 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:00:18 optimizer.py:749] 
I 03-17 22:00:18 optimizer.py:884] Considered resources (1 node):
I 03-17 22:00:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:00:18 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:00:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:00:18 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-2b    0.36       [32m   âœ”[0m     
I 03-17 22:00:18 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:00:18 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:00:18 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2b).
[2mW 03-17 22:00:25 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:00:27 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:00:27 cloud_vm_ray_backend.py:2097] 
W 03-17 22:00:27 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:00:27 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:00:27 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:00:27 optimizer.py:749] 
I 03-17 22:00:27 optimizer.py:884] Considered resources (1 node):
I 03-17 22:00:27 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:00:27 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:00:27 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:00:27 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2c   0.36       [32m   âœ”[0m     
I 03-17 22:00:27 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:00:27 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:00:27 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2c).
[2mW 03-17 22:00:38 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-southeast-2c). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-southeast-2a.[0m
W 03-17 22:00:39 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-southeast-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:00:39 cloud_vm_ray_backend.py:2097] 
W 03-17 22:00:39 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:00:39 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:00:39 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:00:39 optimizer.py:749] 
I 03-17 22:00:39 optimizer.py:884] Considered resources (1 node):
I 03-17 22:00:39 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:00:39 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:00:39 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:00:39 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1d    0.37       [32m   âœ”[0m     
I 03-17 22:00:39 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:00:39 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:00:39 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1d).
W 03-17 22:07:33 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:07:33 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:33 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:33 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:33 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:07:33 optimizer.py:749] 
I 03-17 22:07:33 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:33 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:07:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:33 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2b    0.37       [32m   âœ”[0m     
I 03-17 22:07:33 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:07:33 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:33 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2b).
[2mW 03-17 22:07:41 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:07:42 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:07:42 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:42 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:42 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:42 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:07:42 optimizer.py:749] 
I 03-17 22:07:42 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:42 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:07:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:07:42 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-north-1b   0.37       [32m   âœ”[0m     
I 03-17 22:07:42 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:07:42 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:42 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1b).
[2mW 03-17 22:07:54 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:07:55 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-north-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:07:55 cloud_vm_ray_backend.py:2097] 
W 03-17 22:07:55 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:07:55 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:07:55 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:07:55 optimizer.py:749] 
I 03-17 22:07:55 optimizer.py:884] Considered resources (1 node):
I 03-17 22:07:55 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:07:55 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:07:55 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:07:55 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-southeast-2a   0.38       [32m   âœ”[0m     
I 03-17 22:07:55 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:07:55 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:07:55 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-southeast-2[0m (ap-southeast-2a).
[2mW 03-17 22:08:06 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:08:08 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in ap-southeast-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:08:08 cloud_vm_ray_backend.py:2097] 
W 03-17 22:08:08 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:08:08 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:08:08 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:08:08 optimizer.py:749] 
I 03-17 22:08:08 optimizer.py:884] Considered resources (1 node):
I 03-17 22:08:08 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:08:08 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:08:08 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:08:08 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-west-3b    0.38       [32m   âœ”[0m     
I 03-17 22:08:08 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:08:08 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:08:08 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3b).
[2mW 03-17 22:08:15 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): There is no Spot capacity available that matches your request.[0m
W 03-17 22:08:16 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-west-3b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:08:16 cloud_vm_ray_backend.py:2097] 
W 03-17 22:08:16 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:08:16 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:08:16 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:08:16 optimizer.py:749] 
I 03-17 22:08:16 optimizer.py:884] Considered resources (1 node):
I 03-17 22:08:16 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:08:16 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:08:16 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:08:16 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-1a    0.39       [32m   âœ”[0m     
I 03-17 22:08:16 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:08:16 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:08:16 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1a).
[2mW 03-17 22:11:25 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:11:25 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:11:25 cloud_vm_ray_backend.py:2097] 
W 03-17 22:11:25 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:11:25 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:11:25 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:11:25 optimizer.py:749] 
I 03-17 22:11:25 optimizer.py:884] Considered resources (1 node):
I 03-17 22:11:25 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:11:25 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:11:25 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:11:25 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-east-2a    0.40       [32m   âœ”[0m     
I 03-17 22:11:25 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:11:25 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:11:26 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2a).
[2mW 03-17 22:13:55 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:13:55 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:13:55 cloud_vm_ray_backend.py:2097] 
W 03-17 22:13:55 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:13:56 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:13:56 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:13:56 optimizer.py:749] 
I 03-17 22:13:56 optimizer.py:884] Considered resources (1 node):
I 03-17 22:13:56 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:13:56 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:13:56 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:13:56 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-central-1b   0.40       [32m   âœ”[0m     
I 03-17 22:13:56 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:13:56 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:13:56 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1b).
[2mW 03-17 22:14:06 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:14:07 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-central-1b for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:14:07 cloud_vm_ray_backend.py:2097] 
W 03-17 22:14:07 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:14:07 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:14:07 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:14:07 optimizer.py:749] 
I 03-17 22:14:07 optimizer.py:884] Considered resources (1 node):
I 03-17 22:14:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:14:07 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:14:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:14:07 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2d    0.41       [32m   âœ”[0m     
I 03-17 22:14:07 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:14:07 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:14:07 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2d).
[2mW 03-17 22:14:15 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:14:15 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2d for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:14:15 cloud_vm_ray_backend.py:2097] 
W 03-17 22:14:15 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:14:16 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:14:16 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:14:16 optimizer.py:749] 
I 03-17 22:14:16 optimizer.py:884] Considered resources (1 node):
I 03-17 22:14:16 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:14:16 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN   
I 03-17 22:14:16 optimizer.py:952] ------------------------------------------------------------------------------------------------
I 03-17 22:14:16 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           eu-central-1a   0.41       [32m   âœ”[0m     
I 03-17 22:14:16 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1       0.80                
I 03-17 22:14:16 optimizer.py:952] ------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:14:16 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1a).
[2mW 03-17 22:14:25 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:14:26 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in eu-central-1a for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:14:26 cloud_vm_ray_backend.py:2097] 
W 03-17 22:14:26 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:14:26 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:14:26 optimizer.py:749] [1mEstimated cost: [0m$0.4 / hour
I 03-17 22:14:26 optimizer.py:749] 
I 03-17 22:14:26 optimizer.py:884] Considered resources (1 node):
I 03-17 22:14:26 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:14:26 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 22:14:26 optimizer.py:952] ----------------------------------------------------------------------------------------------
I 03-17 22:14:26 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           us-west-2c    0.41       [32m   âœ”[0m     
I 03-17 22:14:26 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1     0.80                
I 03-17 22:14:26 optimizer.py:952] ----------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:14:26 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2c).
[2mW 03-17 22:14:34 instance.py:243] create_instances: Attempt failed with An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded[0m
W 03-17 22:14:35 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-west-2c for {AWS(cpus=4, {'L4': 1}), AWS([Spot], cpus=4, {'L4': 1})}. 
W 03-17 22:14:35 cloud_vm_ray_backend.py:2097] 
W 03-17 22:14:35 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:14:35 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 22:14:35 optimizer.py:749] [1mEstimated cost: [0m$0.5 / hour
I 03-17 22:14:35 optimizer.py:749] 
I 03-17 22:14:35 optimizer.py:884] Considered resources (1 node):
I 03-17 22:14:35 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:14:35 optimizer.py:952]  CLOUD   INSTANCE          vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE       COST ($)   CHOSEN   
I 03-17 22:14:35 optimizer.py:952] --------------------------------------------------------------------------------------------------
I 03-17 22:14:35 optimizer.py:952]  AWS     g6.xlarge[Spot]   4       16        L4:1           ap-northeast-1a   0.46       [32m   âœ”[0m     
I 03-17 22:14:35 optimizer.py:952]  AWS     g6.xlarge         4       16        L4:1           us-east-1         0.80                
I 03-17 22:14:35 optimizer.py:952] --------------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:14:35 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-1[0m (ap-northeast-1a).
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Waiting for SSH access[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 22:15:04 provisioner.py:451] [2mâ””â”€â”€ [0m[2mInstance is up.[0m
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (1/3 - initializing)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (2/3 - dependencies)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (3/3 - runtime)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:15:33 provisioner.py:632] [0m[32mâœ“ Cluster launched: compute-text-vectors-75.[0m  [2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 22:15:33 execution.py:332] [0mâš™ï¸Ž Syncing files.
<sky-payload>"<rich_init>[bold cyan]Syncing files[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing files[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Syncing files[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing file mounts[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/file_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:15:33 backend_utils.py:1315]   [2mSyncing (to 1 node): s3://skypilot-filemounts-root-726f1974-97bt1exg/job-97bt1exg/workdir -> ~/sky_workdir[0m
I 03-17 22:15:36 cloud_vm_ray_backend.py:4801] [0m[32mâœ“ Synced file_mounts.[0m  [2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/file_mounts.log[0m
<sky-payload>"<rich_update>[bold cyan]Mounting 1 storage[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/storage_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 22:15:36 backend_utils.py:1315]   [2mMounting (to 1 node): s3://sky-text-embeddings-multi-cluster-final-2 -> /output[0m
I 03-17 22:15:39 cloud_vm_ray_backend.py:4892] [0m[32mâœ“ Storage mounted.[0m  [2mView logs: sky api logs -l sky-2025-03-17-21-16-47-955300/storage_mounts.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Running setup[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Running setup[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Running setup[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
I 03-17 22:15:42 cloud_vm_ray_backend.py:3357] [0m[32mâœ“ Setup detached.[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Submitting job[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Submitting job[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Submitting job[/]</rich_start>"</sky-payload>
I 03-17 22:15:43 cloud_vm_ray_backend.py:3546] Multiple resources are specified for the task, using: AWS([Spot], cpus=4, {'L4': 1})
I 03-17 22:15:45 cloud_vm_ray_backend.py:3460] [0mâš™ï¸Ž Job submitted, ID: 1
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 22:15:45 recovery_strategy.py:289] Managed job cluster launched.
I 03-17 22:15:49 utils.py:131] === Checking the job status... ===
I 03-17 22:15:50 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:15:50 utils.py:140] ==================================
I 03-17 22:15:51 state.py:471] Job started.
I 03-17 22:16:12 utils.py:131] === Checking the job status... ===
I 03-17 22:16:12 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:16:12 utils.py:140] ==================================
I 03-17 22:16:32 utils.py:131] === Checking the job status... ===
I 03-17 22:16:33 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:16:33 utils.py:140] ==================================
I 03-17 22:16:54 utils.py:131] === Checking the job status... ===
I 03-17 22:16:54 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:16:54 utils.py:140] ==================================
I 03-17 22:17:15 utils.py:131] === Checking the job status... ===
I 03-17 22:17:16 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:17:16 utils.py:140] ==================================
I 03-17 22:17:36 utils.py:131] === Checking the job status... ===
I 03-17 22:17:37 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 22:17:37 utils.py:140] ==================================
I 03-17 22:17:57 utils.py:131] === Checking the job status... ===
I 03-17 22:17:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:17:58 utils.py:140] ==================================
I 03-17 22:18:18 utils.py:131] === Checking the job status... ===
I 03-17 22:18:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:18:19 utils.py:140] ==================================
I 03-17 22:18:39 utils.py:131] === Checking the job status... ===
I 03-17 22:18:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:18:40 utils.py:140] ==================================
I 03-17 22:19:01 utils.py:131] === Checking the job status... ===
I 03-17 22:19:02 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:19:02 utils.py:140] ==================================
I 03-17 22:19:22 utils.py:131] === Checking the job status... ===
I 03-17 22:19:23 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:19:23 utils.py:140] ==================================
I 03-17 22:19:43 utils.py:131] === Checking the job status... ===
I 03-17 22:19:45 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:19:45 utils.py:140] ==================================
I 03-17 22:20:05 utils.py:131] === Checking the job status... ===
I 03-17 22:20:06 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:20:06 utils.py:140] ==================================
I 03-17 22:20:26 utils.py:131] === Checking the job status... ===
I 03-17 22:20:27 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:20:27 utils.py:140] ==================================
I 03-17 22:20:47 utils.py:131] === Checking the job status... ===
I 03-17 22:20:48 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:20:48 utils.py:140] ==================================
I 03-17 22:21:08 utils.py:131] === Checking the job status... ===
I 03-17 22:21:09 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:21:09 utils.py:140] ==================================
I 03-17 22:21:29 utils.py:131] === Checking the job status... ===
I 03-17 22:21:33 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:21:33 utils.py:140] ==================================
I 03-17 22:21:53 utils.py:131] === Checking the job status... ===
I 03-17 22:21:55 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:21:55 utils.py:140] ==================================
I 03-17 22:22:15 utils.py:131] === Checking the job status... ===
I 03-17 22:22:18 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:22:18 utils.py:140] ==================================
I 03-17 22:22:38 utils.py:131] === Checking the job status... ===
I 03-17 22:22:39 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:22:39 utils.py:140] ==================================
I 03-17 22:23:00 utils.py:131] === Checking the job status... ===
I 03-17 22:23:00 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:23:00 utils.py:140] ==================================
I 03-17 22:23:21 utils.py:131] === Checking the job status... ===
I 03-17 22:23:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:23:22 utils.py:140] ==================================
I 03-17 22:23:42 utils.py:131] === Checking the job status... ===
I 03-17 22:23:43 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:23:43 utils.py:140] ==================================
I 03-17 22:24:03 utils.py:131] === Checking the job status... ===
I 03-17 22:24:04 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:24:04 utils.py:140] ==================================
I 03-17 22:24:24 utils.py:131] === Checking the job status... ===
I 03-17 22:24:25 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:24:25 utils.py:140] ==================================
I 03-17 22:24:45 utils.py:131] === Checking the job status... ===
I 03-17 22:24:46 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:24:46 utils.py:140] ==================================
I 03-17 22:25:06 utils.py:131] === Checking the job status... ===
I 03-17 22:25:07 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:25:07 utils.py:140] ==================================
I 03-17 22:25:27 utils.py:131] === Checking the job status... ===
I 03-17 22:25:28 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:25:28 utils.py:140] ==================================
I 03-17 22:25:48 utils.py:131] === Checking the job status... ===
I 03-17 22:25:49 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:25:49 utils.py:140] ==================================
I 03-17 22:26:09 utils.py:131] === Checking the job status... ===
I 03-17 22:26:10 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:26:10 utils.py:140] ==================================
I 03-17 22:26:30 utils.py:131] === Checking the job status... ===
I 03-17 22:26:31 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:26:31 utils.py:140] ==================================
I 03-17 22:26:51 utils.py:131] === Checking the job status... ===
I 03-17 22:26:52 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:26:52 utils.py:140] ==================================
I 03-17 22:27:12 utils.py:131] === Checking the job status... ===
I 03-17 22:27:13 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:27:13 utils.py:140] ==================================
I 03-17 22:27:33 utils.py:131] === Checking the job status... ===
I 03-17 22:27:34 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:27:34 utils.py:140] ==================================
I 03-17 22:27:54 utils.py:131] === Checking the job status... ===
I 03-17 22:27:55 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:27:55 utils.py:140] ==================================
I 03-17 22:28:15 utils.py:131] === Checking the job status... ===
I 03-17 22:28:16 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:28:16 utils.py:140] ==================================
I 03-17 22:28:36 utils.py:131] === Checking the job status... ===
I 03-17 22:28:37 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:28:37 utils.py:140] ==================================
I 03-17 22:28:57 utils.py:131] === Checking the job status... ===
I 03-17 22:28:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:28:58 utils.py:140] ==================================
I 03-17 22:29:18 utils.py:131] === Checking the job status... ===
I 03-17 22:29:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:29:19 utils.py:140] ==================================
I 03-17 22:29:39 utils.py:131] === Checking the job status... ===
I 03-17 22:29:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:29:40 utils.py:140] ==================================
I 03-17 22:30:00 utils.py:131] === Checking the job status... ===
I 03-17 22:30:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:30:01 utils.py:140] ==================================
I 03-17 22:30:21 utils.py:131] === Checking the job status... ===
I 03-17 22:30:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:30:22 utils.py:140] ==================================
I 03-17 22:30:42 utils.py:131] === Checking the job status... ===
I 03-17 22:30:43 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:30:43 utils.py:140] ==================================
I 03-17 22:31:04 utils.py:131] === Checking the job status... ===
I 03-17 22:31:04 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:31:04 utils.py:140] ==================================
I 03-17 22:31:25 utils.py:131] === Checking the job status... ===
I 03-17 22:31:25 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:31:25 utils.py:140] ==================================
I 03-17 22:31:46 utils.py:131] === Checking the job status... ===
I 03-17 22:31:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:31:47 utils.py:140] ==================================
I 03-17 22:32:07 utils.py:131] === Checking the job status... ===
I 03-17 22:32:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:32:08 utils.py:140] ==================================
I 03-17 22:32:28 utils.py:131] === Checking the job status... ===
I 03-17 22:32:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:32:29 utils.py:140] ==================================
I 03-17 22:32:49 utils.py:131] === Checking the job status... ===
I 03-17 22:32:50 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:32:50 utils.py:140] ==================================
I 03-17 22:33:10 utils.py:131] === Checking the job status... ===
I 03-17 22:33:11 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:33:11 utils.py:140] ==================================
I 03-17 22:33:31 utils.py:131] === Checking the job status... ===
I 03-17 22:33:32 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:33:32 utils.py:140] ==================================
I 03-17 22:33:52 utils.py:131] === Checking the job status... ===
I 03-17 22:33:53 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:33:53 utils.py:140] ==================================
I 03-17 22:34:13 utils.py:131] === Checking the job status... ===
I 03-17 22:34:14 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:34:14 utils.py:140] ==================================
I 03-17 22:34:34 utils.py:131] === Checking the job status... ===
I 03-17 22:34:35 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:34:35 utils.py:140] ==================================
I 03-17 22:34:55 utils.py:131] === Checking the job status... ===
I 03-17 22:34:56 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:34:56 utils.py:140] ==================================
I 03-17 22:35:16 utils.py:131] === Checking the job status... ===
I 03-17 22:35:17 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:35:17 utils.py:140] ==================================
I 03-17 22:35:37 utils.py:131] === Checking the job status... ===
I 03-17 22:35:38 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:35:38 utils.py:140] ==================================
I 03-17 22:35:58 utils.py:131] === Checking the job status... ===
I 03-17 22:35:59 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:35:59 utils.py:140] ==================================
I 03-17 22:36:19 utils.py:131] === Checking the job status... ===
I 03-17 22:36:20 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:36:20 utils.py:140] ==================================
I 03-17 22:36:40 utils.py:131] === Checking the job status... ===
I 03-17 22:36:41 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:36:41 utils.py:140] ==================================
I 03-17 22:37:01 utils.py:131] === Checking the job status... ===
I 03-17 22:37:02 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:37:02 utils.py:140] ==================================
I 03-17 22:37:22 utils.py:131] === Checking the job status... ===
I 03-17 22:37:23 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:37:23 utils.py:140] ==================================
I 03-17 22:37:43 utils.py:131] === Checking the job status... ===
I 03-17 22:37:44 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:37:44 utils.py:140] ==================================
I 03-17 22:38:04 utils.py:131] === Checking the job status... ===
I 03-17 22:38:05 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:38:05 utils.py:140] ==================================
I 03-17 22:38:25 utils.py:131] === Checking the job status... ===
I 03-17 22:38:26 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 22:38:26 utils.py:140] ==================================
I 03-17 22:38:46 utils.py:131] === Checking the job status... ===
I 03-17 22:38:47 utils.py:137] Job status: JobStatus.SUCCEEDED
I 03-17 22:38:47 utils.py:140] ==================================
I 03-17 22:38:48 state.py:561] Job succeeded.
I 03-17 22:38:48 controller.py:238] Managed job 75 (task: 0) SUCCEEDED. Cleaning up the cluster compute-text-vectors-75.
E 03-17 22:38:50 controller_utils.py:376] Failed to find the logs for the user program at ~/sky_logs/managed_jobs/sky-2025-03-17-21-16-47-955300/run.log.
I 03-17 22:38:50 controller.py:117] 
I 03-17 22:38:50 controller.py:117] == End of logs (ID: 75) ==
I 03-17 22:38:59 state.py:656] Cancellation skipped, job is already terminal
I 03-17 22:38:59 state.py:677] Cancellation skipped, job is not CANCELLING
I 03-17 22:39:01 controller.py:552] Killing controller process 34158.
I 03-17 22:39:01 controller.py:560] Controller process 34158 killed.
I 03-17 22:39:01 controller.py:562] Cleaning up any cluster for job 75.
I 03-17 22:39:01 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-97bt1exg
<sky-payload>"<rich_init>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-97bt1exg[/][/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-97bt1exg[/][/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-97bt1exg[/][/]</rich_start>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 22:39:03 storage.py:1505] [32mDeleted S3 bucket skypilot-filemounts-root-726f1974-97bt1exg.[0m
I 03-17 22:39:03 controller.py:571] Cluster of managed job 75 has been cleaned up.
