I 03-17 20:21:58 controller.py:59] DAG:
I 03-17 20:21:58 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 20:21:58 controller.py:59]   resources: AWS(cpus=4, {'L4': 1})]
I 03-17 20:21:58 controller.py:195] Submitted managed job 140 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-20-21-58-490718_compute-text-vectors_140-0
I 03-17 20:21:58 controller.py:199] Started monitoring.
I 03-17 20:21:58 state.py:451] Launching the spot cluster...
I 03-17 20:21:58 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 20:21:59 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:21:59 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:21:59 optimizer.py:749] 
I 03-17 20:21:59 optimizer.py:884] Considered resources (1 node):
I 03-17 20:21:59 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:21:59 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:21:59 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:21:59 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-1     0.80       [32m   âœ”[0m     
I 03-17 20:21:59 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:21:59 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1a,us-east-1b,us-east-1c,us-east-1d).
[2mW 03-17 20:22:02 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:09 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:10 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:10 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:10 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:10 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:10 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:10 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:22:10 optimizer.py:749] 
I 03-17 20:22:10 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:10 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:10 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:22:10 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:10 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-2     0.80       [32m   âœ”[0m     
I 03-17 20:22:10 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:10 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2a,us-east-2b,us-east-2c).
[2mW 03-17 20:22:13 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:14 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:15 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:16 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:16 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:16 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:16 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:16 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:22:16 optimizer.py:749] 
I 03-17 20:22:16 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:16 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:16 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:22:16 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:16 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-west-2     0.80       [32m   âœ”[0m     
I 03-17 20:22:16 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:16 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2a,us-west-2b,us-west-2c,us-west-2d).
[2mW 03-17 20:22:25 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:26 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:40 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:41 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:42 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-west-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:42 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:42 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:42 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:42 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 20:22:42 optimizer.py:749] 
I 03-17 20:22:42 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:42 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:42 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:22:42 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:42 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-north-1    0.85       [32m   âœ”[0m     
I 03-17 20:22:42 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:42 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a,eu-north-1b).
[2mW 03-17 20:22:49 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:52 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:53 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-north-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:53 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:53 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:53 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:53 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 20:22:53 optimizer.py:749] 
I 03-17 20:22:53 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:53 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:22:53 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 20:22:53 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:22:53 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ca-central-1   0.89       [32m   âœ”[0m     
I 03-17 20:22:53 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:53 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a,ca-central-1b).
[2mW 03-17 20:22:55 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:57 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:57 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ca-central-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:57 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:57 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:57 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:57 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 20:22:57 optimizer.py:749] 
I 03-17 20:22:57 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:57 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:57 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:22:57 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:57 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-south-1    0.97       [32m   âœ”[0m     
I 03-17 20:22:57 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:57 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a,ap-south-1b).
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Waiting for SSH access[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:23:38 provisioner.py:451] [2mâ””â”€â”€ [0m[2mInstance is up.[0m
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (1/3 - initializing)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (2/3 - dependencies)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (3/3 - runtime)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:24:06 provisioner.py:632] [0m[32mâœ“ Cluster launched: compute-text-vectors-140.[0m  [2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 20:24:06 execution.py:332] [0mâš™ï¸Ž Syncing files.
<sky-payload>"<rich_init>[bold cyan]Syncing files[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing files[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Syncing files[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing file mounts[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/file_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:24:06 backend_utils.py:1315]   [2mSyncing (to 1 node): s3://skypilot-filemounts-root-726f1974-2rzj7iyf/job-2rzj7iyf/workdir -> ~/sky_workdir[0m
I 03-17 20:24:09 cloud_vm_ray_backend.py:4801] [0m[32mâœ“ Synced file_mounts.[0m  [2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/file_mounts.log[0m
<sky-payload>"<rich_update>[bold cyan]Mounting 1 storage[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/storage_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:24:09 backend_utils.py:1315]   [2mMounting (to 1 node): s3://sky-text-embeddings-multi-cluster-final -> /output[0m
E 03-17 20:24:10 subprocess_utils.py:151] Installing goofys...
E 03-17 20:24:10 subprocess_utils.py:151] --2025-03-17 20:24:10--  https://github.com/romilbhardwaj/goofys/releases/download/0.24.0-romilb-upstream/goofys
E 03-17 20:24:10 subprocess_utils.py:151] Resolving github.com (github.com)... 20.207.73.82
E 03-17 20:24:10 subprocess_utils.py:151] Connecting to github.com (github.com)|20.207.73.82|:443... connected.
E 03-17 20:24:10 subprocess_utils.py:151] HTTP request sent, awaiting response... 500 Internal Server Error
E 03-17 20:24:10 subprocess_utils.py:151] 2025-03-17 20:24:10 ERROR 500: Internal Server Error.
E 03-17 20:24:10 subprocess_utils.py:151] 
E 03-17 20:24:10 subprocess_utils.py:151] Mount path /output does not exist. Creating...
E 03-17 20:24:10 subprocess_utils.py:151] Mounting  to /output with goofys...
E 03-17 20:24:10 subprocess_utils.py:151] /home/ubuntu/.sky/mount_234873.sh: line 38: /usr/local/bin/goofys: Permission denied
E 03-17 20:24:10 subprocess_utils.py:151] 
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 20:24:10 recovery_strategy.py:331] Failed to launch a cluster with error: sky.exceptions.CommandError: Command to mount failed with return code 126.
I 03-17 20:24:10 recovery_strategy.py:331] [31m[0m[2m----- CMD -----
I 03-17 20:24:10 recovery_strategy.py:331] echo '
I 03-17 20:24:10 recovery_strategy.py:331] #!/usr/bin/env bash
I 03-17 20:24:10 recovery_strategy.py:331] set -e
I 03-17 20:24:10 recovery_strategy.py:331] 
I 03-17 20:24:10 recovery_strategy.py:331] { [ "$(whoami)" == "root" ] && function sudo() { "$@"; } || true; }
I 03-17 20:24:10 recovery_strategy.py:331] 
I 03-17 20:24:10 recovery_strategy.py:331] MOUNT_PATH=/output
I 03-17 20:24:10 recovery_strategy.py:331] MOUNT_BINARY=goofys
I 03-17 20:24:10 recovery_strategy.py:331] 
I 03-17 20:24:10 recovery_strategy.py:331] # Check if path is already mounted
I 03-17 20:24:10 recovery_strategy.py:331] if grep -q $MOUNT_PATH /proc/mounts ; then
I 03-17 20:24:10 recovery_strategy.py:331]     echo "Path already mounted - unmounting..."
I 03-17 20:24:10 recovery_strategy.py:331]     fusermount -uz "$MOUNT_PATH"
I 03-17 20:24:10 recovery_strategy.py:331]     echo "Successfully unmounted $MOUNT_PATH."
I 03-17 20:24:10 recovery_strategy.py:331] fi
I 03-17 20:24:10 recovery_strategy.py:331] 
I 03-17 20:24:10 recovery_strategy.py:331] # Install MOUNT_BINARY if not already installed
I 03-17 20:24:10 recovery_strategy.py:331] if [ -x "$(command -v goofys)" ]; then
I 03-17 20:24:10 recovery_strategy.py:331]   echo "$MOUNT_BINARY already installed. Proceeding..."
I 03-17 20:24:10 recovery_strategy.py:331] else
I 03-17 20:24:10 recovery_strategy.py:331]   echo "Installing $MOUNT_BINARY..."
I 03-17 20:24:10 recovery_strategy.py:331]   ARCH=$(uname -m) && if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then   echo "goofys is not supported on $ARCH" &&   exit 133; else   ARCH_SUFFIX="amd64"; fi && sudo wget -nc https://github.com/romilbhardwaj/goofys/releases/download/0.24.0-romilb-upstream/goofys -O /usr/local/bin/goofys && sudo chmod 755 /usr/local/bin/goofys
I 03-17 20:24:10 recovery_strategy.py:331] fi
I 03-17 20:24:10 recovery_strategy.py:331] 
I 03-17 20:24:10 recovery_strategy.py:331] # Check if mount path exists
I 03-17 20:24:10 recovery_strategy.py:331] if [ ! -d "$MOUNT_PATH" ]; then
I 03-17 20:24:10 recovery_strategy.py:331]   echo "Mount path $MOUNT_PATH does not exist. Creating..."
I 03-17 20:24:10 recovery_strategy.py:331]   sudo mkdir -p $MOUNT_PATH
I 03-17 20:24:10 recovery_strategy.py:331]   sudo chmod 777 $MOUNT_PATH
I 03-17 20:24:10 recovery_strategy.py:331] else
I 03-17 20:24:10 recovery_strategy.py:331]   # Check if mount path contains files
I 03-17 20:24:10 recovery_strategy.py:331]   if [ "$(ls -A $MOUNT_PATH)" ]; then
I 03-17 20:24:10 recovery_strategy.py:331]     echo "Mount path $MOUNT_PATH is not empty. Please mount to another path or remove it first."
I 03-17 20:24:10 recovery_strategy.py:331]     exit 42
I 03-17 20:24:10 recovery_strategy.py:331]   fi
I 03-17 20:24:10 recovery_strategy.py:331] fi
I 03-17 20:24:10 recovery_strategy.py:331] echo "Mounting $SOURCE_BUCKET to $MOUNT_PATH with $MOUNT_BINARY..."
I 03-17 20:24:10 recovery_strategy.py:331] goofys -o allow_other --stat-cache-ttl 5s --type-cache-ttl 5s sky-text-embeddings-multi-cluster-final /output
I 03-17 20:24:10 recovery_strategy.py:331] echo "Mounting done."
I 03-17 20:24:10 recovery_strategy.py:331] ' > ~/.sky/mount_234873.sh && chmod +x ~/.sky/mount_234873.sh && bash ~/.sky/mount_234873.sh && rm ~/.sky/mount_234873.sh
I 03-17 20:24:10 recovery_strategy.py:331] ----- CMD END -----
I 03-17 20:24:10 recovery_strategy.py:331] [0m[31mFailed to run command before rsync s3://sky-text-embeddings-multi-cluster-final -> /output. [0m[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/storage_mounts.log[0m[0m)
I 03-17 20:24:10 recovery_strategy.py:334]   Traceback: Traceback (most recent call last):
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/jobs/recovery_strategy.py", line 280, in _launch
I 03-17 20:24:10 recovery_strategy.py:334]     execution.launch(
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 457, in _record
I 03-17 20:24:10 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 457, in _record
I 03-17 20:24:10 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/execution.py", line 532, in launch
I 03-17 20:24:10 recovery_strategy.py:334]     return _execute(
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/execution.py", line 338, in _execute
I 03-17 20:24:10 recovery_strategy.py:334]     backend.sync_file_mounts(handle, task.file_mounts,
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 457, in _record
I 03-17 20:24:10 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 437, in _record
I 03-17 20:24:10 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/backends/backend.py", line 101, in sync_file_mounts
I 03-17 20:24:10 recovery_strategy.py:334]     return self._sync_file_mounts(handle, all_file_mounts, storage_mounts)
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/backends/cloud_vm_ray_backend.py", line 3214, in _sync_file_mounts
I 03-17 20:24:10 recovery_strategy.py:334]     self._execute_storage_mounts(handle, storage_mounts)
I 03-17 20:24:10 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/backends/cloud_vm_ray_backend.py", line 4884, in _execute_storage_mounts
I 03-17 20:24:10 recovery_strategy.py:334]     raise exceptions.CommandError(
I 03-17 20:24:10 recovery_strategy.py:334] sky.exceptions.CommandError: Command to mount failed with return code 126.
I 03-17 20:24:10 recovery_strategy.py:334] [31m[0m[2m----- CMD -----
I 03-17 20:24:10 recovery_strategy.py:334] echo '
I 03-17 20:24:10 recovery_strategy.py:334] #!/usr/bin/env bash
I 03-17 20:24:10 recovery_strategy.py:334] set -e
I 03-17 20:24:10 recovery_strategy.py:334] 
I 03-17 20:24:10 recovery_strategy.py:334] { [ "$(whoami)" == "root" ] && function sudo() { "$@"; } || true; }
I 03-17 20:24:10 recovery_strategy.py:334] 
I 03-17 20:24:10 recovery_strategy.py:334] MOUNT_PATH=/output
I 03-17 20:24:10 recovery_strategy.py:334] MOUNT_BINARY=goofys
I 03-17 20:24:10 recovery_strategy.py:334] 
I 03-17 20:24:10 recovery_strategy.py:334] # Check if path is already mounted
I 03-17 20:24:10 recovery_strategy.py:334] if grep -q $MOUNT_PATH /proc/mounts ; then
I 03-17 20:24:10 recovery_strategy.py:334]     echo "Path already mounted - unmounting..."
I 03-17 20:24:10 recovery_strategy.py:334]     fusermount -uz "$MOUNT_PATH"
I 03-17 20:24:10 recovery_strategy.py:334]     echo "Successfully unmounted $MOUNT_PATH."
I 03-17 20:24:10 recovery_strategy.py:334] fi
I 03-17 20:24:10 recovery_strategy.py:334] 
I 03-17 20:24:10 recovery_strategy.py:334] # Install MOUNT_BINARY if not already installed
I 03-17 20:24:10 recovery_strategy.py:334] if [ -x "$(command -v goofys)" ]; then
I 03-17 20:24:10 recovery_strategy.py:334]   echo "$MOUNT_BINARY already installed. Proceeding..."
I 03-17 20:24:10 recovery_strategy.py:334] else
I 03-17 20:24:10 recovery_strategy.py:334]   echo "Installing $MOUNT_BINARY..."
I 03-17 20:24:10 recovery_strategy.py:334]   ARCH=$(uname -m) && if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then   echo "goofys is not supported on $ARCH" &&   exit 133; else   ARCH_SUFFIX="amd64"; fi && sudo wget -nc https://github.com/romilbhardwaj/goofys/releases/download/0.24.0-romilb-upstream/goofys -O /usr/local/bin/goofys && sudo chmod 755 /usr/local/bin/goofys
I 03-17 20:24:10 recovery_strategy.py:334] fi
I 03-17 20:24:10 recovery_strategy.py:334] 
I 03-17 20:24:10 recovery_strategy.py:334] # Check if mount path exists
I 03-17 20:24:10 recovery_strategy.py:334] if [ ! -d "$MOUNT_PATH" ]; then
I 03-17 20:24:10 recovery_strategy.py:334]   echo "Mount path $MOUNT_PATH does not exist. Creating..."
I 03-17 20:24:10 recovery_strategy.py:334]   sudo mkdir -p $MOUNT_PATH
I 03-17 20:24:10 recovery_strategy.py:334]   sudo chmod 777 $MOUNT_PATH
I 03-17 20:24:10 recovery_strategy.py:334] else
I 03-17 20:24:10 recovery_strategy.py:334]   # Check if mount path contains files
I 03-17 20:24:10 recovery_strategy.py:334]   if [ "$(ls -A $MOUNT_PATH)" ]; then
I 03-17 20:24:10 recovery_strategy.py:334]     echo "Mount path $MOUNT_PATH is not empty. Please mount to another path or remove it first."
I 03-17 20:24:10 recovery_strategy.py:334]     exit 42
I 03-17 20:24:10 recovery_strategy.py:334]   fi
I 03-17 20:24:10 recovery_strategy.py:334] fi
I 03-17 20:24:10 recovery_strategy.py:334] echo "Mounting $SOURCE_BUCKET to $MOUNT_PATH with $MOUNT_BINARY..."
I 03-17 20:24:10 recovery_strategy.py:334] goofys -o allow_other --stat-cache-ttl 5s --type-cache-ttl 5s sky-text-embeddings-multi-cluster-final /output
I 03-17 20:24:10 recovery_strategy.py:334] echo "Mounting done."
I 03-17 20:24:10 recovery_strategy.py:334] ' > ~/.sky/mount_234873.sh && chmod +x ~/.sky/mount_234873.sh && bash ~/.sky/mount_234873.sh && rm ~/.sky/mount_234873.sh
I 03-17 20:24:10 recovery_strategy.py:334] ----- CMD END -----
I 03-17 20:24:10 recovery_strategy.py:334] [0m[31mFailed to run command before rsync s3://sky-text-embeddings-multi-cluster-final -> /output. [0m[2mView logs: sky api logs -l sky-2025-03-17-20-21-59-093313/storage_mounts.log[0m[0m
I 03-17 20:24:10 recovery_strategy.py:334] 
I 03-17 20:24:14 recovery_strategy.py:364] Retrying to launch the cluster in 73.0 seconds.
I 03-17 20:25:28 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-2rzj7iyf
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 20:25:28 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:25:28 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:25:28 optimizer.py:749] 
I 03-17 20:25:28 optimizer.py:884] Considered resources (1 node):
I 03-17 20:25:28 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:25:28 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:25:28 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:25:28 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-1     0.80       [32m   âœ”[0m     
I 03-17 20:25:28 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:25:28 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1a,us-east-1b,us-east-1c,us-east-1d).
[2mW 03-17 20:25:31 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:25:44 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:26:32 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:26:33 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:26:33 cloud_vm_ray_backend.py:2097] 
W 03-17 20:26:33 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:26:33 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:26:33 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:26:33 optimizer.py:749] 
I 03-17 20:26:33 optimizer.py:884] Considered resources (1 node):
I 03-17 20:26:33 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:26:33 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:26:33 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:26:33 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-2     0.80       [32m   âœ”[0m     
I 03-17 20:26:33 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:26:33 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2a,us-east-2b,us-east-2c).
[2mW 03-17 20:26:36 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:26:44 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:26:45 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:26:45 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:26:45 cloud_vm_ray_backend.py:2097] 
W 03-17 20:26:45 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:26:46 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:26:46 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:26:46 optimizer.py:749] 
I 03-17 20:26:46 optimizer.py:884] Considered resources (1 node):
I 03-17 20:26:46 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:26:46 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:26:46 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:26:46 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-west-2     0.80       [32m   âœ”[0m     
I 03-17 20:26:46 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:26:46 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2a,us-west-2b,us-west-2c,us-west-2d).
[2mW 03-17 20:27:32 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:27:33 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:27:38 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:27:59 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:27:59 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-west-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:27:59 cloud_vm_ray_backend.py:2097] 
W 03-17 20:27:59 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:27:59 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:27:59 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 20:27:59 optimizer.py:749] 
I 03-17 20:27:59 optimizer.py:884] Considered resources (1 node):
I 03-17 20:27:59 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:27:59 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:27:59 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:27:59 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-north-1    0.85       [32m   âœ”[0m     
I 03-17 20:27:59 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:28:00 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a,eu-north-1b).
[2mW 03-17 20:28:07 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:28:21 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:28:22 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-north-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:28:22 cloud_vm_ray_backend.py:2097] 
W 03-17 20:28:22 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:28:22 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:28:22 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 20:28:22 optimizer.py:749] 
I 03-17 20:28:22 optimizer.py:884] Considered resources (1 node):
I 03-17 20:28:22 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:28:22 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 20:28:22 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:28:22 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ca-central-1   0.89       [32m   âœ”[0m     
I 03-17 20:28:22 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:28:22 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a,ca-central-1b).
[2mW 03-17 20:29:30 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:29:31 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:29:32 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ca-central-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:29:32 cloud_vm_ray_backend.py:2097] 
W 03-17 20:29:32 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:29:32 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:29:32 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 20:29:32 optimizer.py:749] 
I 03-17 20:29:32 optimizer.py:884] Considered resources (1 node):
I 03-17 20:29:32 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:29:32 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:29:32 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:29:32 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-south-1    0.97       [32m   âœ”[0m     
I 03-17 20:29:32 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:29:32 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a,ap-south-1b).
[2mW 03-17 20:29:40 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-south-1a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-south-1b.[0m
[2mW 03-17 20:29:42 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-south-1b). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-south-1a.[0m
W 03-17 20:29:43 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-south-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:29:43 cloud_vm_ray_backend.py:2097] 
W 03-17 20:29:43 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:29:43 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:29:43 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 20:29:43 optimizer.py:749] 
I 03-17 20:29:43 optimizer.py:884] Considered resources (1 node):
I 03-17 20:29:43 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 20:29:43 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 20:29:43 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 20:29:43 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 20:29:43 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:29:44 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 20:29:52 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 20:29:55 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 20:29:56 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:29:56 cloud_vm_ray_backend.py:2097] 
W 03-17 20:29:56 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:29:56 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:29:56 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 20:29:56 optimizer.py:749] 
I 03-17 20:29:56 optimizer.py:884] Considered resources (1 node):
I 03-17 20:29:56 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:29:56 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 20:29:56 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:29:56 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-central-1   1.01       [32m   âœ”[0m     
I 03-17 20:29:56 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:29:56 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-central-1[0m (eu-central-1a,eu-central-1b).
[2mW 03-17 20:30:03 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:30:05 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:30:06 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-central-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:30:06 cloud_vm_ray_backend.py:2097] 
W 03-17 20:30:06 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:30:06 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:30:06 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 20:30:06 optimizer.py:749] 
I 03-17 20:30:06 optimizer.py:884] Considered resources (1 node):
I 03-17 20:30:06 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:30:06 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:30:06 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:30:06 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-west-2     1.02       [32m   âœ”[0m     
I 03-17 20:30:06 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:30:06 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-2[0m (eu-west-2a,eu-west-2b).
[2mW 03-17 20:30:11 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:30:12 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:30:13 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-west-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:30:13 cloud_vm_ray_backend.py:2097] 
W 03-17 20:30:13 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:30:13 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:30:13 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 20:30:13 optimizer.py:749] 
I 03-17 20:30:13 optimizer.py:884] Considered resources (1 node):
I 03-17 20:30:13 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:30:13 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:30:13 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:30:13 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-west-3     1.02       [32m   âœ”[0m     
I 03-17 20:30:13 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:30:14 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-west-3[0m (eu-west-3b,eu-west-3c).
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Waiting for SSH access[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:30:42 provisioner.py:451] [2mâ””â”€â”€ [0m[2mInstance is up.[0m
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (1/3 - initializing)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (2/3 - dependencies)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (3/3 - runtime)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:31:20 provisioner.py:632] [0m[32mâœ“ Cluster launched: compute-text-vectors-140.[0m  [2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 20:31:20 execution.py:332] [0mâš™ï¸Ž Syncing files.
<sky-payload>"<rich_init>[bold cyan]Syncing files[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing files[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Syncing files[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing file mounts[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/file_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:31:21 backend_utils.py:1315]   [2mSyncing (to 1 node): s3://skypilot-filemounts-root-726f1974-2rzj7iyf/job-2rzj7iyf/workdir -> ~/sky_workdir[0m
I 03-17 20:31:24 cloud_vm_ray_backend.py:4801] [0m[32mâœ“ Synced file_mounts.[0m  [2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/file_mounts.log[0m
<sky-payload>"<rich_update>[bold cyan]Mounting 1 storage[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/storage_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:31:24 backend_utils.py:1315]   [2mMounting (to 1 node): s3://sky-text-embeddings-multi-cluster-final -> /output[0m
I 03-17 20:31:26 cloud_vm_ray_backend.py:4892] [0m[32mâœ“ Storage mounted.[0m  [2mView logs: sky api logs -l sky-2025-03-17-20-25-28-186221/storage_mounts.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Running setup[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Running setup[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Running setup[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
I 03-17 20:31:28 cloud_vm_ray_backend.py:3357] [0m[32mâœ“ Setup detached.[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Submitting job[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Submitting job[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Submitting job[/]</rich_start>"</sky-payload>
I 03-17 20:31:30 cloud_vm_ray_backend.py:3460] [0mâš™ï¸Ž Job submitted, ID: 1
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 20:31:31 recovery_strategy.py:289] Managed job cluster launched.
I 03-17 20:31:34 utils.py:131] === Checking the job status... ===
I 03-17 20:31:35 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:31:35 utils.py:140] ==================================
I 03-17 20:31:36 state.py:471] Job started.
I 03-17 20:31:56 utils.py:131] === Checking the job status... ===
I 03-17 20:31:57 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:31:57 utils.py:140] ==================================
I 03-17 20:32:17 utils.py:131] === Checking the job status... ===
I 03-17 20:32:18 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:32:18 utils.py:140] ==================================
I 03-17 20:32:38 utils.py:131] === Checking the job status... ===
I 03-17 20:32:39 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:32:39 utils.py:140] ==================================
I 03-17 20:32:59 utils.py:131] === Checking the job status... ===
I 03-17 20:33:00 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:33:00 utils.py:140] ==================================
I 03-17 20:33:20 utils.py:131] === Checking the job status... ===
I 03-17 20:33:20 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:33:20 utils.py:140] ==================================
I 03-17 20:33:41 utils.py:131] === Checking the job status... ===
I 03-17 20:33:41 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:33:41 utils.py:140] ==================================
I 03-17 20:34:01 utils.py:131] === Checking the job status... ===
I 03-17 20:34:02 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:34:02 utils.py:140] ==================================
I 03-17 20:34:22 utils.py:131] === Checking the job status... ===
I 03-17 20:34:23 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:34:23 utils.py:140] ==================================
I 03-17 20:34:43 utils.py:131] === Checking the job status... ===
I 03-17 20:34:44 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:34:44 utils.py:140] ==================================
I 03-17 20:35:04 utils.py:131] === Checking the job status... ===
I 03-17 20:35:05 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:35:05 utils.py:140] ==================================
I 03-17 20:35:25 utils.py:131] === Checking the job status... ===
I 03-17 20:35:26 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:35:26 utils.py:140] ==================================
I 03-17 20:35:46 utils.py:131] === Checking the job status... ===
I 03-17 20:35:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:35:47 utils.py:140] ==================================
I 03-17 20:36:07 utils.py:131] === Checking the job status... ===
I 03-17 20:36:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:36:08 utils.py:140] ==================================
I 03-17 20:36:28 utils.py:131] === Checking the job status... ===
I 03-17 20:36:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:36:29 utils.py:140] ==================================
I 03-17 20:36:49 utils.py:131] === Checking the job status... ===
I 03-17 20:36:50 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:36:50 utils.py:140] ==================================
I 03-17 20:37:10 utils.py:131] === Checking the job status... ===
I 03-17 20:37:11 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:37:11 utils.py:140] ==================================
I 03-17 20:37:31 utils.py:131] === Checking the job status... ===
I 03-17 20:37:34 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:37:34 utils.py:140] ==================================
I 03-17 20:37:54 utils.py:131] === Checking the job status... ===
I 03-17 20:37:56 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:37:56 utils.py:140] ==================================
I 03-17 20:38:16 utils.py:131] === Checking the job status... ===
I 03-17 20:38:18 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:38:18 utils.py:140] ==================================
I 03-17 20:38:38 utils.py:131] === Checking the job status... ===
I 03-17 20:38:39 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:38:39 utils.py:140] ==================================
I 03-17 20:38:59 utils.py:131] === Checking the job status... ===
I 03-17 20:39:00 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:39:00 utils.py:140] ==================================
I 03-17 20:39:20 utils.py:131] === Checking the job status... ===
I 03-17 20:39:21 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:39:21 utils.py:140] ==================================
I 03-17 20:39:41 utils.py:131] === Checking the job status... ===
I 03-17 20:39:42 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:39:42 utils.py:140] ==================================
I 03-17 20:40:02 utils.py:131] === Checking the job status... ===
I 03-17 20:40:03 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:40:03 utils.py:140] ==================================
I 03-17 20:40:23 utils.py:131] === Checking the job status... ===
I 03-17 20:40:24 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:40:24 utils.py:140] ==================================
I 03-17 20:40:44 utils.py:131] === Checking the job status... ===
I 03-17 20:40:44 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:40:44 utils.py:140] ==================================
I 03-17 20:41:05 utils.py:131] === Checking the job status... ===
I 03-17 20:41:05 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:41:05 utils.py:140] ==================================
I 03-17 20:41:25 utils.py:131] === Checking the job status... ===
I 03-17 20:41:26 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:41:26 utils.py:140] ==================================
I 03-17 20:41:46 utils.py:131] === Checking the job status... ===
I 03-17 20:41:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:41:47 utils.py:140] ==================================
I 03-17 20:42:07 utils.py:131] === Checking the job status... ===
I 03-17 20:42:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:42:08 utils.py:140] ==================================
I 03-17 20:42:28 utils.py:131] === Checking the job status... ===
I 03-17 20:42:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:42:29 utils.py:140] ==================================
I 03-17 20:42:49 utils.py:131] === Checking the job status... ===
I 03-17 20:42:50 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:42:50 utils.py:140] ==================================
I 03-17 20:43:10 utils.py:131] === Checking the job status... ===
I 03-17 20:43:11 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:43:11 utils.py:140] ==================================
I 03-17 20:43:31 utils.py:131] === Checking the job status... ===
I 03-17 20:43:32 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:43:32 utils.py:140] ==================================
I 03-17 20:43:52 utils.py:131] === Checking the job status... ===
I 03-17 20:43:53 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:43:53 utils.py:140] ==================================
I 03-17 20:44:13 utils.py:131] === Checking the job status... ===
I 03-17 20:44:14 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:44:14 utils.py:140] ==================================
I 03-17 20:44:34 utils.py:131] === Checking the job status... ===
I 03-17 20:44:34 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:44:34 utils.py:140] ==================================
I 03-17 20:44:55 utils.py:131] === Checking the job status... ===
I 03-17 20:44:55 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:44:55 utils.py:140] ==================================
I 03-17 20:45:15 utils.py:131] === Checking the job status... ===
I 03-17 20:45:16 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:45:16 utils.py:140] ==================================
I 03-17 20:45:36 utils.py:131] === Checking the job status... ===
I 03-17 20:45:37 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:45:37 utils.py:140] ==================================
I 03-17 20:45:57 utils.py:131] === Checking the job status... ===
I 03-17 20:45:58 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:45:58 utils.py:140] ==================================
I 03-17 20:46:18 utils.py:131] === Checking the job status... ===
I 03-17 20:46:19 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:46:19 utils.py:140] ==================================
I 03-17 20:46:39 utils.py:131] === Checking the job status... ===
I 03-17 20:46:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:46:40 utils.py:140] ==================================
I 03-17 20:47:00 utils.py:131] === Checking the job status... ===
I 03-17 20:47:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:47:01 utils.py:140] ==================================
I 03-17 20:47:21 utils.py:131] === Checking the job status... ===
I 03-17 20:47:21 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:47:21 utils.py:140] ==================================
I 03-17 20:47:41 utils.py:131] === Checking the job status... ===
I 03-17 20:47:42 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:47:42 utils.py:140] ==================================
I 03-17 20:48:02 utils.py:131] === Checking the job status... ===
I 03-17 20:48:03 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:48:03 utils.py:140] ==================================
I 03-17 20:48:23 utils.py:131] === Checking the job status... ===
I 03-17 20:48:24 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:48:24 utils.py:140] ==================================
I 03-17 20:48:44 utils.py:131] === Checking the job status... ===
I 03-17 20:48:45 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:48:45 utils.py:140] ==================================
I 03-17 20:49:05 utils.py:131] === Checking the job status... ===
I 03-17 20:49:06 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:49:06 utils.py:140] ==================================
I 03-17 20:49:26 utils.py:131] === Checking the job status... ===
I 03-17 20:49:27 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:49:27 utils.py:140] ==================================
I 03-17 20:49:47 utils.py:131] === Checking the job status... ===
I 03-17 20:49:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:49:47 utils.py:140] ==================================
I 03-17 20:50:08 utils.py:131] === Checking the job status... ===
I 03-17 20:50:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:50:08 utils.py:140] ==================================
I 03-17 20:50:28 utils.py:131] === Checking the job status... ===
I 03-17 20:50:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:50:29 utils.py:140] ==================================
I 03-17 20:50:49 utils.py:131] === Checking the job status... ===
I 03-17 20:50:50 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:50:50 utils.py:140] ==================================
I 03-17 20:51:10 utils.py:131] === Checking the job status... ===
I 03-17 20:51:11 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:51:11 utils.py:140] ==================================
I 03-17 20:51:31 utils.py:131] === Checking the job status... ===
I 03-17 20:51:32 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:51:32 utils.py:140] ==================================
I 03-17 20:51:52 utils.py:131] === Checking the job status... ===
I 03-17 20:51:53 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:51:53 utils.py:140] ==================================
I 03-17 20:52:13 utils.py:131] === Checking the job status... ===
I 03-17 20:52:14 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:52:14 utils.py:140] ==================================
I 03-17 20:52:34 utils.py:131] === Checking the job status... ===
I 03-17 20:52:35 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:52:35 utils.py:140] ==================================
